/*
 * generated by Xtext 2.35.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SaddStandaloneSetup extends SaddStandaloneSetupGenerated {

	public static void doSetup() {
		new SaddStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
