/**
 * generated by Xtext 2.35.0
 */
package xtext.sadd;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alternatives</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.sadd.Alternatives#getAlternatives <em>Alternatives</em>}</li>
 *   <li>{@link xtext.sadd.Alternatives#getSelectedalternatives <em>Selectedalternatives</em>}</li>
 * </ul>
 *
 * @see xtext.sadd.SaddPackage#getAlternatives()
 * @model
 * @generated
 */
public interface Alternatives extends EObject
{
  /**
   * Returns the value of the '<em><b>Alternatives</b></em>' containment reference list.
   * The list contents are of type {@link xtext.sadd.Alternative}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alternatives</em>' containment reference list.
   * @see xtext.sadd.SaddPackage#getAlternatives_Alternatives()
   * @model containment="true"
   * @generated
   */
  EList<Alternative> getAlternatives();

  /**
   * Returns the value of the '<em><b>Selectedalternatives</b></em>' reference list.
   * The list contents are of type {@link xtext.sadd.Alternative}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selectedalternatives</em>' reference list.
   * @see xtext.sadd.SaddPackage#getAlternatives_Selectedalternatives()
   * @model
   * @generated
   */
  EList<Alternative> getSelectedalternatives();

} // Alternatives
