/**
 * generated by Xtext 2.35.0
 */
package xtext.sadd;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Category</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.sadd.Category#getSecadd <em>Secadd</em>}</li>
 * </ul>
 *
 * @see xtext.sadd.SaddPackage#getCategory()
 * @model
 * @generated
 */
public interface Category extends ProjCatSADD
{
  /**
   * Returns the value of the '<em><b>Secadd</b></em>' reference list.
   * The list contents are of type {@link xtext.sadd.SecurityADD}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secadd</em>' reference list.
   * @see xtext.sadd.SaddPackage#getCategory_Secadd()
   * @model
   * @generated
   */
  EList<SecurityADD> getSecadd();

} // Category
