/**
 * generated by Xtext 2.35.0
 */
package xtext.sadd;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.sadd.Model#getImports <em>Imports</em>}</li>
 *   <li>{@link xtext.sadd.Model#getProjcatsadd <em>Projcatsadd</em>}</li>
 * </ul>
 *
 * @see xtext.sadd.SaddPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link xtext.sadd.Import}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see xtext.sadd.SaddPackage#getModel_Imports()
   * @model containment="true"
   * @generated
   */
  EList<Import> getImports();

  /**
   * Returns the value of the '<em><b>Projcatsadd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projcatsadd</em>' containment reference.
   * @see #setProjcatsadd(ProjCatSADD)
   * @see xtext.sadd.SaddPackage#getModel_Projcatsadd()
   * @model containment="true"
   * @generated
   */
  ProjCatSADD getProjcatsadd();

  /**
   * Sets the value of the '{@link xtext.sadd.Model#getProjcatsadd <em>Projcatsadd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projcatsadd</em>' containment reference.
   * @see #getProjcatsadd()
   * @generated
   */
  void setProjcatsadd(ProjCatSADD value);

} // Model
