/*
 * generated by Xtext 2.35.0
 */
package xtext.semcomdt.swhumanfactor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.semcomdt.swhumanfactor.HumanfactorRuntimeModule;
import xtext.semcomdt.swhumanfactor.HumanfactorStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HumanfactorIdeSetup extends HumanfactorStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HumanfactorRuntimeModule(), new HumanfactorIdeModule()));
	}
	
}
