/*
 * generated by Xtext 2.35.0
 */
package xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.DecisionmakingRuntimeModule;
import xtext.DecisionmakingStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DecisionmakingIdeSetup extends DecisionmakingStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DecisionmakingRuntimeModule(), new DecisionmakingIdeModule()));
	}
	
}
