/*
 * generated by Xtext 2.35.0
 */
package xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import xtext.ide.contentassist.antlr.internal.InternalDecisionmakingParser;
import xtext.services.DecisionmakingGrammarAccess;

public class DecisionmakingParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DecisionmakingGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DecisionmakingGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getLibDesRunAccess().getAlternatives(), "rule__LibDesRun__Alternatives");
			builder.put(grammarAccess.getRuleAccess().getAlternatives(), "rule__Rule__Alternatives");
			builder.put(grammarAccess.getPredefinedRuleAccess().getAlternatives(), "rule__PredefinedRule__Alternatives");
			builder.put(grammarAccess.getStratAccess().getAlternatives(), "rule__Strat__Alternatives");
			builder.put(grammarAccess.getSolutionSelectionKindAccess().getAlternatives(), "rule__SolutionSelectionKind__Alternatives");
			builder.put(grammarAccess.getBOOLEANAccess().getAlternatives(), "rule__BOOLEAN__Alternatives");
			builder.put(grammarAccess.getGroupDecisionSessionAccess().getGroup(), "rule__GroupDecisionSession__Group__0");
			builder.put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
			builder.put(grammarAccess.getLibraryAccess().getGroup_0(), "rule__Library__Group_0__0");
			builder.put(grammarAccess.getStrategyAccess().getGroup(), "rule__Strategy__Group__0");
			builder.put(grammarAccess.getStrategyAccess().getGroup_6(), "rule__Strategy__Group_6__0");
			builder.put(grammarAccess.getStrategyPredefinedAccess().getGroup(), "rule__StrategyPredefined__Group__0");
			builder.put(grammarAccess.getStrategyPredefinedAccess().getGroup_4(), "rule__StrategyPredefined__Group_4__0");
			builder.put(grammarAccess.getStrategyDecisionRuleAccess().getGroup(), "rule__StrategyDecisionRule__Group__0");
			builder.put(grammarAccess.getPredefinedDecisionRuleAccess().getGroup(), "rule__PredefinedDecisionRule__Group__0");
			builder.put(grammarAccess.getStrategyAlgorithmAccess().getGroup(), "rule__StrategyAlgorithm__Group__0");
			builder.put(grammarAccess.getDecisionRuleAccess().getGroup(), "rule__DecisionRule__Group__0");
			builder.put(grammarAccess.getAlgorithmAccess().getGroup(), "rule__Algorithm__Group__0");
			builder.put(grammarAccess.getDesignTimeAccess().getGroup(), "rule__DesignTime__Group__0");
			builder.put(grammarAccess.getDecisionSupportAccess().getGroup(), "rule__DecisionSupport__Group__0");
			builder.put(grammarAccess.getStratAccess().getGroup_1(), "rule__Strat__Group_1__0");
			builder.put(grammarAccess.getStratAccess().getGroup_1_4(), "rule__Strat__Group_1_4__0");
			builder.put(grammarAccess.getRunTimeAccess().getGroup(), "rule__RunTime__Group__0");
			builder.put(grammarAccess.getSADDResultAccess().getGroup(), "rule__SADDResult__Group__0");
			builder.put(grammarAccess.getAlternativePreferenceAccess().getGroup(), "rule__AlternativePreference__Group__0");
			builder.put(grammarAccess.getPreferenceAccess().getGroup(), "rule__Preference__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getGroupDecisionSessionAccess().getImportsAssignment_0(), "rule__GroupDecisionSession__ImportsAssignment_0");
			builder.put(grammarAccess.getGroupDecisionSessionAccess().getConceptAssignment_1(), "rule__GroupDecisionSession__ConceptAssignment_1");
			builder.put(grammarAccess.getLibDesRunAccess().getLibraryAssignment_0(), "rule__LibDesRun__LibraryAssignment_0");
			builder.put(grammarAccess.getLibDesRunAccess().getDesigntimeAssignment_1(), "rule__LibDesRun__DesigntimeAssignment_1");
			builder.put(grammarAccess.getLibDesRunAccess().getRuntimeAssignment_2(), "rule__LibDesRun__RuntimeAssignment_2");
			builder.put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
			builder.put(grammarAccess.getLibraryAccess().getNameAssignment_0_1(), "rule__Library__NameAssignment_0_1");
			builder.put(grammarAccess.getLibraryAccess().getDecisionrulesAssignment_0_2(), "rule__Library__DecisionrulesAssignment_0_2");
			builder.put(grammarAccess.getLibraryAccess().getAlgorithmsAssignment_1(), "rule__Library__AlgorithmsAssignment_1");
			builder.put(grammarAccess.getLibraryAccess().getStrategiesAssignment_2(), "rule__Library__StrategiesAssignment_2");
			builder.put(grammarAccess.getStrategyAccess().getNameAssignment_1(), "rule__Strategy__NameAssignment_1");
			builder.put(grammarAccess.getStrategyAccess().getSolutionSelectedChosenAssignment_3(), "rule__Strategy__SolutionSelectedChosenAssignment_3");
			builder.put(grammarAccess.getStrategyAccess().getRulesAssignment_5(), "rule__Strategy__RulesAssignment_5");
			builder.put(grammarAccess.getStrategyAccess().getRulesAssignment_6_1(), "rule__Strategy__RulesAssignment_6_1");
			builder.put(grammarAccess.getStrategyPredefinedAccess().getNameAssignment_1(), "rule__StrategyPredefined__NameAssignment_1");
			builder.put(grammarAccess.getStrategyPredefinedAccess().getRulesAssignment_3(), "rule__StrategyPredefined__RulesAssignment_3");
			builder.put(grammarAccess.getStrategyPredefinedAccess().getRulesAssignment_4_1(), "rule__StrategyPredefined__RulesAssignment_4_1");
			builder.put(grammarAccess.getStrategyDecisionRuleAccess().getDecisionruleAssignment_1(), "rule__StrategyDecisionRule__DecisionruleAssignment_1");
			builder.put(grammarAccess.getStrategyDecisionRuleAccess().getTeamprofilesAssignment_3(), "rule__StrategyDecisionRule__TeamprofilesAssignment_3");
			builder.put(grammarAccess.getPredefinedDecisionRuleAccess().getDecisionruleAssignment_1(), "rule__PredefinedDecisionRule__DecisionruleAssignment_1");
			builder.put(grammarAccess.getStrategyAlgorithmAccess().getAlgorithmAssignment_1(), "rule__StrategyAlgorithm__AlgorithmAssignment_1");
			builder.put(grammarAccess.getDecisionRuleAccess().getNameAssignment_1(), "rule__DecisionRule__NameAssignment_1");
			builder.put(grammarAccess.getDecisionRuleAccess().getSolutionselectionacceptedAssignment_3(), "rule__DecisionRule__SolutionselectionacceptedAssignment_3");
			builder.put(grammarAccess.getDecisionRuleAccess().getDescriptionAssignment_5(), "rule__DecisionRule__DescriptionAssignment_5");
			builder.put(grammarAccess.getAlgorithmAccess().getNameAssignment_1(), "rule__Algorithm__NameAssignment_1");
			builder.put(grammarAccess.getAlgorithmAccess().getSolutionselectionacceptedAssignment_3(), "rule__Algorithm__SolutionselectionacceptedAssignment_3");
			builder.put(grammarAccess.getAlgorithmAccess().getConsidersTPAssignment_6(), "rule__Algorithm__ConsidersTPAssignment_6");
			builder.put(grammarAccess.getAlgorithmAccess().getDescriptionAssignment_7(), "rule__Algorithm__DescriptionAssignment_7");
			builder.put(grammarAccess.getDesignTimeAccess().getDecisionsupportAssignment_2(), "rule__DesignTime__DecisionsupportAssignment_2");
			builder.put(grammarAccess.getDecisionSupportAccess().getNameAssignment_1(), "rule__DecisionSupport__NameAssignment_1");
			builder.put(grammarAccess.getDecisionSupportAccess().getMakedecisionforAssignment_3(), "rule__DecisionSupport__MakedecisionforAssignment_3");
			builder.put(grammarAccess.getDecisionSupportAccess().getStratAssignment_5(), "rule__DecisionSupport__StratAssignment_5");
			builder.put(grammarAccess.getStratAccess().getStratAssignment_1_1(), "rule__Strat__StratAssignment_1_1");
			builder.put(grammarAccess.getStratAccess().getSolutionSelectedChosenAssignment_1_3(), "rule__Strat__SolutionSelectedChosenAssignment_1_3");
			builder.put(grammarAccess.getStratAccess().getTeamprofilesAssignment_1_4_1(), "rule__Strat__TeamprofilesAssignment_1_4_1");
			builder.put(grammarAccess.getRunTimeAccess().getDecisionsupportAssignment_2(), "rule__RunTime__DecisionsupportAssignment_2");
			builder.put(grammarAccess.getRunTimeAccess().getCategoryAssignment_4(), "rule__RunTime__CategoryAssignment_4");
			builder.put(grammarAccess.getRunTimeAccess().getSaddresultAssignment_6(), "rule__RunTime__SaddresultAssignment_6");
			builder.put(grammarAccess.getSADDResultAccess().getSaddAssignment_0(), "rule__SADDResult__SaddAssignment_0");
			builder.put(grammarAccess.getSADDResultAccess().getAltpreferencesAssignment_2(), "rule__SADDResult__AltpreferencesAssignment_2");
			builder.put(grammarAccess.getAlternativePreferenceAccess().getAlternativeAssignment_0(), "rule__AlternativePreference__AlternativeAssignment_0");
			builder.put(grammarAccess.getAlternativePreferenceAccess().getPreferencesAssignment_2(), "rule__AlternativePreference__PreferencesAssignment_2");
			builder.put(grammarAccess.getPreferenceAccess().getActorAssignment_0(), "rule__Preference__ActorAssignment_0");
			builder.put(grammarAccess.getPreferenceAccess().getValueAssignment_2(), "rule__Preference__ValueAssignment_2");
			builder.put(grammarAccess.getPreferenceAccess().getRationaleAssignment_4(), "rule__Preference__RationaleAssignment_4");
			builder.put(grammarAccess.getLibraryAccess().getUnorderedGroup(), "rule__Library__UnorderedGroup");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DecisionmakingGrammarAccess grammarAccess;

	@Override
	protected InternalDecisionmakingParser createParser() {
		InternalDecisionmakingParser result = new InternalDecisionmakingParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DecisionmakingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DecisionmakingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
