/*
 * generated by Xtext 2.35.0
 */
package xtext.ui;

import com.google.inject.Injector;
import decisionmaking.ui.internal.DecisionmakingActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DecisionmakingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DecisionmakingActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DecisionmakingActivator activator = DecisionmakingActivator.getInstance();
		return activator != null ? activator.getInjector(DecisionmakingActivator.XTEXT_DECISIONMAKING) : null;
	}

}
