/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity.scoping;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

import com.google.inject.Inject;
import com.google.inject.name.Named;

import semcomdt.swsecurity.decisionmaking.DecisionmakingPackage;
import semcomdt.swsecurity.decisionmaking.RunTime;
import semcomdt.swsecurity.decisionmaking.SADDResult;
import semcomdt.swsecurity.securityadd.Alternative;
import semcomdt.swsecurity.securityadd.Category;
import semcomdt.swsecurity.securityadd.SecurityADD;

/**
 * This class contains custom scoping description.
 * 
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class DecisionmakingScopeProvider extends AbstractDecisionmakingScopeProvider {

	@Inject
	@Named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE)
	private IScopeProvider delegate;

	@Override
	public IScope getScope(EObject context, EReference reference) {

//		if (context instanceof Preference && reference == DecisionmakingPackage.Literals.PREFERENCE__ALTERNATIVE) {

		// Preference pref = (Preference) context;
//			EcoreUtil2.getAllReferencedObjects(pref, SecurityaddPackage.Literals.SECURITY_ADD__ALTERNATIVES);
//            EObject rootElement = EcoreUtil2.getRootContainer(context);
//            List<Alternative> candidates = EcoreUtil2.getAllContentsOfType(rootElement, Alternative.class);
//            List<Alternative> candidates =((SecurityADD) pref.getAlternative().eContainer()).getAlternatives();
//            List<Alternative> candidates = ((DesignTime) alternative.eContainer().eContainer()).getSadd().stream(SecurityADD sadd -> sadd);
		// List<Element> listRefines = ((Solution)
		// solelement.eContainer()).getRefines().stream().map(solref ->
		// solref.getSolutionelements()).flatMap(List::stream).toList();
//            return Scopes.scopeFor(candidates);
//		}
		// We make sure that elements refines elements of one level before
//		if (context instanceof RunTime && reference == DecisionmakingPackage.Literals.RUN_TIME__SADDRESULT) {
//		}
		if (context instanceof RunTime && reference == DecisionmakingPackage.Literals.SADD_RESULT__SADD) {
//		if (context instanceof SADDResult && reference == DecisionmakingPackage.Literals.SADD_RESULT__SADD) {
			Category solelement = ((RunTime) context).getCategory();
//			solelement.getCategory().getSecadd();
//			EObject rootElement = EcoreUtil2.getRootContainer(context);
			List<SecurityADD> candidates = solelement.getSecadd();
//			List<SecurityADD> candidates = EcoreUtil2.getAllContentsOfType(solelement, SecurityADD.class);
//			candidates = candidates.stream().filter(rt -> rt.eContainer().equals(solelement)).toList();
//			List<Alternative> listRefines = ((SecurityADD) solelement.getSadd()).getAlternatives();// .stream().map(solref
			// ->
			// solref).flatMap(List::stream).toList()
			return Scopes.scopeFor(candidates);
		}
		// Error reference when filtering like this
		if (context instanceof SADDResult
				&& reference == DecisionmakingPackage.Literals.ALTERNATIVE_PREFERENCE__ALTERNATIVE) {

			SecurityADD secadd = ((SADDResult) context).getSadd();

//			EObject rootElement = EcoreUtil2.getRootContainer(context);
			List<Alternative> possibletargets = EcoreUtil2.getAllContentsOfType(secadd, Alternative.class);
//			possibletargets = possibletargets.stream().filter(elem -> ((Solution) elem.eContainer()).equals(solution))
//					.toList();
//			return Scopes.scopeFor(possibletargets);

			IScope scope = delegate.getScope(context, reference);
			Iterable<IEObjectDescription> scopes = scope.getAllElements();
//			Iterables.removeIf(scopes,
//					element -> element.getQualifiedName().getFirstSegment().equals(secadd.getName()));
//			Scopes.scopedElementsFor(scopes);
//			return Scopes.scopeFor(scopes);

//
////			List<Object> scopes = new ArrayList<Object>();
//			List<String> scopes = new ArrayList<String>();
//
//			scope.getAllElements().forEach(
//					sco -> System.out.println(sco.getQualifiedName().getFirstSegment().equals(secadd.getName())));
//			for (IEObjectDescription element : scope.getAllElements()) {
//				if (element.getQualifiedName().getFirstSegment().equals(secadd.getName())) {
//
//					scopes.add(element.getQualifiedName().toString());
//				}
//			}
//			List<Alternative> candidates = secadd.getAlternatives();
//			scope.getAllElements();
//			List<Alternative> newalts = new ArrayList<Alternative>();
//			for (Alternative alt : candidates) {
//				Alternative newalt = alt;
//				newalt.setName(secadd.getName() + "." + alt.getName());
//				newalts.add(newalt);
//			}
//			candidates.getFirst().setName(secadd.getName() + "." + candidates.getFirst().getName());
//			return scope;
		}
		return super.getScope(context, reference);

	}
}
