grammar semcomdt.swsecurity.Decisionmaking with org.eclipse.xtext.common.Terminals

generate decisionmaking "http://www.swsecurity.semcomdt/Decisionmaking"


import "http://www.semcomdt.swhumanfactor/Teamprofile" as TP
import "http://www.swsecurity.semcomdt/Securityadd" as SADD

GroupDecisionSession:
	(imports+=Import*)
	concept=LibDesRun
	
;
LibDesRun :
	library=Library |
	designtime=DesignTime |
	runtime=RunTime
;
Import :
	"import" importURI=STRING
;
Library :
	"Library" name=ID
	decisionrules+=DecisionRule* &
	algorithms+=Algorithm* &
	strategies+=StrategyPredefined* 	
;

/**
 * Used to define the strategy we want, giving it a name and assigning it to an SADD concept
 * Rules are then defined between brackets
 */
Strategy:
	'Strategy' name=ID  "withPreferenceIndication" solutionSelectedChosen=SolutionSelectionKind "{" 
	rules+=Rule*	("then" rules+=Rule*)* "}"
;
StrategyPredefined:
	'Strategy' name=ID  "{" 
	rules+=PredefinedRule*	("then" rules+=PredefinedRule*)* "}"
;
/**
 * Rule to be able to choose between an algorithm and a decision rule
 */
Rule :
	 StrategyAlgorithm | StrategyDecisionRule
;
PredefinedRule:
	StrategyAlgorithm | PredefinedDecisionRule
;
/**
 * DecisionRule reference rule where we link an already defined decision rule to our strategy.
 * We must also define to which team profile(s) it is applied
 */
StrategyDecisionRule :
	"decisionrule"  decisionrule=[DecisionRule|QualifiedName] "for" teamprofiles+=[TP::Profile|QualifiedName]+
;
PredefinedDecisionRule:
	"decisionrule"  decisionrule=[DecisionRule|QualifiedName] 
;
/**
 * Algorithm reference rule where we link an already defined algorithm to our strategy
 * If team profiles are considered in the algorithm then they are all considered 
 */
StrategyAlgorithm :
	"algorithm"  algorithm=[Algorithm|QualifiedName]
;

/**
 * Definition of a decision rule with its name and a description
 */
DecisionRule :
	"decisionrule" name=ID "(" solutionselectionaccepted+=SolutionSelectionKind* ")" description=STRING 
;
/**
 * Definition of an algorithm rule with its name and a description
 */
Algorithm :
	"algorithm" name=ID "(" solutionselectionaccepted+=SolutionSelectionKind* ")" "considersTP" considersTP=BOOLEAN description=STRING  

;

DesignTime :
	"DesignTime" 
	"{"
		decisionsupport=DecisionSupport
	"}"
;
DecisionSupport:
	"DecisionSupport" name=ID "decidesFor" makedecisionfor+=[SADD::Category|QualifiedName]+ 
		"{" strat+=Strat*"}"
;
Strat :
	Strategy |
	"Strategy" strat=[StrategyPredefined|QualifiedName] "withPreferenceIndication" solutionSelectedChosen=SolutionSelectionKind ("for" teamprofiles+=[TP::Profile|QualifiedName]+)? 
;

RunTime:
	"Runtime" "using" decisionsupport=[DecisionSupport|QualifiedName] "{"
	category=[SADD::Category|QualifiedName] "{"
		saddresult+=SADDResult+
	"}"
	"}"
;
SADDResult:
	sadd=[SADD::SecurityADD|QualifiedName] "{"
		altpreferences+=AlternativePreference+
	"}"
;
AlternativePreference:
	alternative=[SADD::Alternative|QualifiedName] "{"
		preferences+=Preference+
	"}"
;
Preference :
	actor=[TP::Actor] "selected" value=INT "rationale" rationale=STRING //"for" alternative=[SADD::Alternative|QualifiedName]
;
enum SolutionSelectionKind :
	ranking="Ranking" |
	rating="Rating" |
	yesno="YesNo"
	
;

QualifiedName:
	ID ('.' ID)*
;

enum BOOLEAN:
	no="no" | yes="yes"
;