/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DecisionmakingStandaloneSetup extends DecisionmakingStandaloneSetupGenerated {

	public static void doSetup() {
		new DecisionmakingStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
