/*
 * generated by Xtext 2.35.0
 */
package xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import teamprofile.ui.internal.TeamprofileActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TeamprofileExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TeamprofileActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TeamprofileActivator activator = TeamprofileActivator.getInstance();
		return activator != null ? activator.getInjector(TeamprofileActivator.XTEXT_TEAMPROFILE) : null;
	}

}
