/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algorithm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.Algorithm#getName <em>Name</em>}</li>
 *   <li>{@link xtext.decisionmaking.Algorithm#getSolutionselectionaccepted <em>Solutionselectionaccepted</em>}</li>
 *   <li>{@link xtext.decisionmaking.Algorithm#getConsidersTP <em>Considers TP</em>}</li>
 *   <li>{@link xtext.decisionmaking.Algorithm#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see xtext.decisionmaking.DecisionmakingPackage#getAlgorithm()
 * @model
 * @generated
 */
public interface Algorithm extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.decisionmaking.DecisionmakingPackage#getAlgorithm_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.Algorithm#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Solutionselectionaccepted</b></em>' attribute list.
   * The list contents are of type {@link xtext.decisionmaking.SolutionSelectionKind}.
   * The literals are from the enumeration {@link xtext.decisionmaking.SolutionSelectionKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Solutionselectionaccepted</em>' attribute list.
   * @see xtext.decisionmaking.SolutionSelectionKind
   * @see xtext.decisionmaking.DecisionmakingPackage#getAlgorithm_Solutionselectionaccepted()
   * @model unique="false"
   * @generated
   */
  EList<SolutionSelectionKind> getSolutionselectionaccepted();

  /**
   * Returns the value of the '<em><b>Considers TP</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.decisionmaking.BOOLEAN}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Considers TP</em>' attribute.
   * @see xtext.decisionmaking.BOOLEAN
   * @see #setConsidersTP(BOOLEAN)
   * @see xtext.decisionmaking.DecisionmakingPackage#getAlgorithm_ConsidersTP()
   * @model
   * @generated
   */
  BOOLEAN getConsidersTP();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.Algorithm#getConsidersTP <em>Considers TP</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Considers TP</em>' attribute.
   * @see xtext.decisionmaking.BOOLEAN
   * @see #getConsidersTP()
   * @generated
   */
  void setConsidersTP(BOOLEAN value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see xtext.decisionmaking.DecisionmakingPackage#getAlgorithm_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.Algorithm#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // Algorithm
