/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import xtext.sadd.Category;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decision Support</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.DecisionSupport#getName <em>Name</em>}</li>
 *   <li>{@link xtext.decisionmaking.DecisionSupport#getMakedecisionfor <em>Makedecisionfor</em>}</li>
 *   <li>{@link xtext.decisionmaking.DecisionSupport#getStrat <em>Strat</em>}</li>
 * </ul>
 *
 * @see xtext.decisionmaking.DecisionmakingPackage#getDecisionSupport()
 * @model
 * @generated
 */
public interface DecisionSupport extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.decisionmaking.DecisionmakingPackage#getDecisionSupport_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.DecisionSupport#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Makedecisionfor</b></em>' reference list.
   * The list contents are of type {@link xtext.sadd.Category}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Makedecisionfor</em>' reference list.
   * @see xtext.decisionmaking.DecisionmakingPackage#getDecisionSupport_Makedecisionfor()
   * @model
   * @generated
   */
  EList<Category> getMakedecisionfor();

  /**
   * Returns the value of the '<em><b>Strat</b></em>' containment reference list.
   * The list contents are of type {@link xtext.decisionmaking.Strat}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strat</em>' containment reference list.
   * @see xtext.decisionmaking.DecisionmakingPackage#getDecisionSupport_Strat()
   * @model containment="true"
   * @generated
   */
  EList<Strat> getStrat();

} // DecisionSupport
