/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see xtext.decisionmaking.DecisionmakingPackage
 * @generated
 */
public interface DecisionmakingFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DecisionmakingFactory eINSTANCE = xtext.decisionmaking.impl.DecisionmakingFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Group Decision Session</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Group Decision Session</em>'.
   * @generated
   */
  GroupDecisionSession createGroupDecisionSession();

  /**
   * Returns a new object of class '<em>Lib Des Run</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lib Des Run</em>'.
   * @generated
   */
  LibDesRun createLibDesRun();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>Library</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Library</em>'.
   * @generated
   */
  Library createLibrary();

  /**
   * Returns a new object of class '<em>Strategy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Strategy</em>'.
   * @generated
   */
  Strategy createStrategy();

  /**
   * Returns a new object of class '<em>Strategy Predefined</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Strategy Predefined</em>'.
   * @generated
   */
  StrategyPredefined createStrategyPredefined();

  /**
   * Returns a new object of class '<em>Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule</em>'.
   * @generated
   */
  Rule createRule();

  /**
   * Returns a new object of class '<em>Predefined Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Predefined Rule</em>'.
   * @generated
   */
  PredefinedRule createPredefinedRule();

  /**
   * Returns a new object of class '<em>Strategy Decision Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Strategy Decision Rule</em>'.
   * @generated
   */
  StrategyDecisionRule createStrategyDecisionRule();

  /**
   * Returns a new object of class '<em>Predefined Decision Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Predefined Decision Rule</em>'.
   * @generated
   */
  PredefinedDecisionRule createPredefinedDecisionRule();

  /**
   * Returns a new object of class '<em>Strategy Algorithm</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Strategy Algorithm</em>'.
   * @generated
   */
  StrategyAlgorithm createStrategyAlgorithm();

  /**
   * Returns a new object of class '<em>Decision Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Decision Rule</em>'.
   * @generated
   */
  DecisionRule createDecisionRule();

  /**
   * Returns a new object of class '<em>Algorithm</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithm</em>'.
   * @generated
   */
  Algorithm createAlgorithm();

  /**
   * Returns a new object of class '<em>Design Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Design Time</em>'.
   * @generated
   */
  DesignTime createDesignTime();

  /**
   * Returns a new object of class '<em>Decision Support</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Decision Support</em>'.
   * @generated
   */
  DecisionSupport createDecisionSupport();

  /**
   * Returns a new object of class '<em>Strat</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Strat</em>'.
   * @generated
   */
  Strat createStrat();

  /**
   * Returns a new object of class '<em>Run Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Run Time</em>'.
   * @generated
   */
  RunTime createRunTime();

  /**
   * Returns a new object of class '<em>SADD Result</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SADD Result</em>'.
   * @generated
   */
  SADDResult createSADDResult();

  /**
   * Returns a new object of class '<em>Alternative Preference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alternative Preference</em>'.
   * @generated
   */
  AlternativePreference createAlternativePreference();

  /**
   * Returns a new object of class '<em>Preference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Preference</em>'.
   * @generated
   */
  Preference createPreference();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DecisionmakingPackage getDecisionmakingPackage();

} //DecisionmakingFactory
