/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xtext.decisionmaking.DecisionmakingFactory
 * @model kind="package"
 * @generated
 */
public interface DecisionmakingPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "decisionmaking";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Decisionmaking.xtext";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "decisionmaking";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DecisionmakingPackage eINSTANCE = xtext.decisionmaking.impl.DecisionmakingPackageImpl.init();

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.GroupDecisionSessionImpl <em>Group Decision Session</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.GroupDecisionSessionImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getGroupDecisionSession()
   * @generated
   */
  int GROUP_DECISION_SESSION = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_DECISION_SESSION__IMPORTS = 0;

  /**
   * The feature id for the '<em><b>Concept</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_DECISION_SESSION__CONCEPT = 1;

  /**
   * The number of structural features of the '<em>Group Decision Session</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_DECISION_SESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.LibDesRunImpl <em>Lib Des Run</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.LibDesRunImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getLibDesRun()
   * @generated
   */
  int LIB_DES_RUN = 1;

  /**
   * The feature id for the '<em><b>Library</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIB_DES_RUN__LIBRARY = 0;

  /**
   * The feature id for the '<em><b>Designtime</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIB_DES_RUN__DESIGNTIME = 1;

  /**
   * The feature id for the '<em><b>Runtime</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIB_DES_RUN__RUNTIME = 2;

  /**
   * The number of structural features of the '<em>Lib Des Run</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIB_DES_RUN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.ImportImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORT_URI = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.LibraryImpl <em>Library</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.LibraryImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getLibrary()
   * @generated
   */
  int LIBRARY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARY__NAME = 0;

  /**
   * The feature id for the '<em><b>Decisionrules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARY__DECISIONRULES = 1;

  /**
   * The feature id for the '<em><b>Algorithms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARY__ALGORITHMS = 2;

  /**
   * The feature id for the '<em><b>Strategies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARY__STRATEGIES = 3;

  /**
   * The number of structural features of the '<em>Library</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.StratImpl <em>Strat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.StratImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getStrat()
   * @generated
   */
  int STRAT = 15;

  /**
   * The feature id for the '<em><b>Strat</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAT__STRAT = 0;

  /**
   * The feature id for the '<em><b>Solution Selected Chosen</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAT__SOLUTION_SELECTED_CHOSEN = 1;

  /**
   * The feature id for the '<em><b>Teamprofiles</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAT__TEAMPROFILES = 2;

  /**
   * The number of structural features of the '<em>Strat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.StrategyImpl <em>Strategy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.StrategyImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getStrategy()
   * @generated
   */
  int STRATEGY = 4;

  /**
   * The feature id for the '<em><b>Strat</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY__STRAT = STRAT__STRAT;

  /**
   * The feature id for the '<em><b>Solution Selected Chosen</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY__SOLUTION_SELECTED_CHOSEN = STRAT__SOLUTION_SELECTED_CHOSEN;

  /**
   * The feature id for the '<em><b>Teamprofiles</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY__TEAMPROFILES = STRAT__TEAMPROFILES;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY__NAME = STRAT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY__RULES = STRAT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Strategy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_FEATURE_COUNT = STRAT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.StrategyPredefinedImpl <em>Strategy Predefined</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.StrategyPredefinedImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getStrategyPredefined()
   * @generated
   */
  int STRATEGY_PREDEFINED = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_PREDEFINED__NAME = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_PREDEFINED__RULES = 1;

  /**
   * The number of structural features of the '<em>Strategy Predefined</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_PREDEFINED_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.RuleImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getRule()
   * @generated
   */
  int RULE = 6;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.PredefinedRuleImpl <em>Predefined Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.PredefinedRuleImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getPredefinedRule()
   * @generated
   */
  int PREDEFINED_RULE = 7;

  /**
   * The number of structural features of the '<em>Predefined Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDEFINED_RULE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.StrategyDecisionRuleImpl <em>Strategy Decision Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.StrategyDecisionRuleImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getStrategyDecisionRule()
   * @generated
   */
  int STRATEGY_DECISION_RULE = 8;

  /**
   * The feature id for the '<em><b>Decisionrule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_DECISION_RULE__DECISIONRULE = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Teamprofiles</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_DECISION_RULE__TEAMPROFILES = RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Strategy Decision Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_DECISION_RULE_FEATURE_COUNT = RULE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.PredefinedDecisionRuleImpl <em>Predefined Decision Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.PredefinedDecisionRuleImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getPredefinedDecisionRule()
   * @generated
   */
  int PREDEFINED_DECISION_RULE = 9;

  /**
   * The feature id for the '<em><b>Decisionrule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDEFINED_DECISION_RULE__DECISIONRULE = PREDEFINED_RULE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Predefined Decision Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDEFINED_DECISION_RULE_FEATURE_COUNT = PREDEFINED_RULE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.StrategyAlgorithmImpl <em>Strategy Algorithm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.StrategyAlgorithmImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getStrategyAlgorithm()
   * @generated
   */
  int STRATEGY_ALGORITHM = 10;

  /**
   * The feature id for the '<em><b>Algorithm</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_ALGORITHM__ALGORITHM = RULE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Strategy Algorithm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRATEGY_ALGORITHM_FEATURE_COUNT = RULE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.DecisionRuleImpl <em>Decision Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.DecisionRuleImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getDecisionRule()
   * @generated
   */
  int DECISION_RULE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Solutionselectionaccepted</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_RULE__SOLUTIONSELECTIONACCEPTED = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_RULE__DESCRIPTION = 2;

  /**
   * The number of structural features of the '<em>Decision Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.AlgorithmImpl <em>Algorithm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.AlgorithmImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getAlgorithm()
   * @generated
   */
  int ALGORITHM = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__NAME = 0;

  /**
   * The feature id for the '<em><b>Solutionselectionaccepted</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__SOLUTIONSELECTIONACCEPTED = 1;

  /**
   * The feature id for the '<em><b>Considers TP</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__CONSIDERS_TP = 2;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__DESCRIPTION = 3;

  /**
   * The number of structural features of the '<em>Algorithm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.DesignTimeImpl <em>Design Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.DesignTimeImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getDesignTime()
   * @generated
   */
  int DESIGN_TIME = 13;

  /**
   * The feature id for the '<em><b>Decisionsupport</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_TIME__DECISIONSUPPORT = 0;

  /**
   * The number of structural features of the '<em>Design Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGN_TIME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.DecisionSupportImpl <em>Decision Support</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.DecisionSupportImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getDecisionSupport()
   * @generated
   */
  int DECISION_SUPPORT = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_SUPPORT__NAME = 0;

  /**
   * The feature id for the '<em><b>Makedecisionfor</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_SUPPORT__MAKEDECISIONFOR = 1;

  /**
   * The feature id for the '<em><b>Strat</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_SUPPORT__STRAT = 2;

  /**
   * The number of structural features of the '<em>Decision Support</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_SUPPORT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.RunTimeImpl <em>Run Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.RunTimeImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getRunTime()
   * @generated
   */
  int RUN_TIME = 16;

  /**
   * The feature id for the '<em><b>Decisionsupport</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN_TIME__DECISIONSUPPORT = 0;

  /**
   * The feature id for the '<em><b>Category</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN_TIME__CATEGORY = 1;

  /**
   * The feature id for the '<em><b>Saddresult</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN_TIME__SADDRESULT = 2;

  /**
   * The number of structural features of the '<em>Run Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN_TIME_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.SADDResultImpl <em>SADD Result</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.SADDResultImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getSADDResult()
   * @generated
   */
  int SADD_RESULT = 17;

  /**
   * The feature id for the '<em><b>Sadd</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SADD_RESULT__SADD = 0;

  /**
   * The feature id for the '<em><b>Altpreferences</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SADD_RESULT__ALTPREFERENCES = 1;

  /**
   * The number of structural features of the '<em>SADD Result</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SADD_RESULT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.AlternativePreferenceImpl <em>Alternative Preference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.AlternativePreferenceImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getAlternativePreference()
   * @generated
   */
  int ALTERNATIVE_PREFERENCE = 18;

  /**
   * The feature id for the '<em><b>Alternative</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVE_PREFERENCE__ALTERNATIVE = 0;

  /**
   * The feature id for the '<em><b>Preferences</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVE_PREFERENCE__PREFERENCES = 1;

  /**
   * The number of structural features of the '<em>Alternative Preference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVE_PREFERENCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.impl.PreferenceImpl <em>Preference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.impl.PreferenceImpl
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getPreference()
   * @generated
   */
  int PREFERENCE = 19;

  /**
   * The feature id for the '<em><b>Actor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFERENCE__ACTOR = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFERENCE__VALUE = 1;

  /**
   * The feature id for the '<em><b>Rationale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFERENCE__RATIONALE = 2;

  /**
   * The number of structural features of the '<em>Preference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFERENCE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.SolutionSelectionKind <em>Solution Selection Kind</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.SolutionSelectionKind
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getSolutionSelectionKind()
   * @generated
   */
  int SOLUTION_SELECTION_KIND = 20;

  /**
   * The meta object id for the '{@link xtext.decisionmaking.BOOLEAN <em>BOOLEAN</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.decisionmaking.BOOLEAN
   * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getBOOLEAN()
   * @generated
   */
  int BOOLEAN = 21;


  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.GroupDecisionSession <em>Group Decision Session</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group Decision Session</em>'.
   * @see xtext.decisionmaking.GroupDecisionSession
   * @generated
   */
  EClass getGroupDecisionSession();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.decisionmaking.GroupDecisionSession#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see xtext.decisionmaking.GroupDecisionSession#getImports()
   * @see #getGroupDecisionSession()
   * @generated
   */
  EReference getGroupDecisionSession_Imports();

  /**
   * Returns the meta object for the containment reference '{@link xtext.decisionmaking.GroupDecisionSession#getConcept <em>Concept</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Concept</em>'.
   * @see xtext.decisionmaking.GroupDecisionSession#getConcept()
   * @see #getGroupDecisionSession()
   * @generated
   */
  EReference getGroupDecisionSession_Concept();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.LibDesRun <em>Lib Des Run</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lib Des Run</em>'.
   * @see xtext.decisionmaking.LibDesRun
   * @generated
   */
  EClass getLibDesRun();

  /**
   * Returns the meta object for the containment reference '{@link xtext.decisionmaking.LibDesRun#getLibrary <em>Library</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Library</em>'.
   * @see xtext.decisionmaking.LibDesRun#getLibrary()
   * @see #getLibDesRun()
   * @generated
   */
  EReference getLibDesRun_Library();

  /**
   * Returns the meta object for the containment reference '{@link xtext.decisionmaking.LibDesRun#getDesigntime <em>Designtime</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Designtime</em>'.
   * @see xtext.decisionmaking.LibDesRun#getDesigntime()
   * @see #getLibDesRun()
   * @generated
   */
  EReference getLibDesRun_Designtime();

  /**
   * Returns the meta object for the containment reference '{@link xtext.decisionmaking.LibDesRun#getRuntime <em>Runtime</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Runtime</em>'.
   * @see xtext.decisionmaking.LibDesRun#getRuntime()
   * @see #getLibDesRun()
   * @generated
   */
  EReference getLibDesRun_Runtime();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see xtext.decisionmaking.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.Import#getImportURI <em>Import URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import URI</em>'.
   * @see xtext.decisionmaking.Import#getImportURI()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportURI();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.Library <em>Library</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Library</em>'.
   * @see xtext.decisionmaking.Library
   * @generated
   */
  EClass getLibrary();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.Library#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.decisionmaking.Library#getName()
   * @see #getLibrary()
   * @generated
   */
  EAttribute getLibrary_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.decisionmaking.Library#getDecisionrules <em>Decisionrules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Decisionrules</em>'.
   * @see xtext.decisionmaking.Library#getDecisionrules()
   * @see #getLibrary()
   * @generated
   */
  EReference getLibrary_Decisionrules();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.decisionmaking.Library#getAlgorithms <em>Algorithms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Algorithms</em>'.
   * @see xtext.decisionmaking.Library#getAlgorithms()
   * @see #getLibrary()
   * @generated
   */
  EReference getLibrary_Algorithms();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.decisionmaking.Library#getStrategies <em>Strategies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Strategies</em>'.
   * @see xtext.decisionmaking.Library#getStrategies()
   * @see #getLibrary()
   * @generated
   */
  EReference getLibrary_Strategies();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.Strategy <em>Strategy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Strategy</em>'.
   * @see xtext.decisionmaking.Strategy
   * @generated
   */
  EClass getStrategy();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.Strategy#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.decisionmaking.Strategy#getName()
   * @see #getStrategy()
   * @generated
   */
  EAttribute getStrategy_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.decisionmaking.Strategy#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see xtext.decisionmaking.Strategy#getRules()
   * @see #getStrategy()
   * @generated
   */
  EReference getStrategy_Rules();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.StrategyPredefined <em>Strategy Predefined</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Strategy Predefined</em>'.
   * @see xtext.decisionmaking.StrategyPredefined
   * @generated
   */
  EClass getStrategyPredefined();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.StrategyPredefined#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.decisionmaking.StrategyPredefined#getName()
   * @see #getStrategyPredefined()
   * @generated
   */
  EAttribute getStrategyPredefined_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.decisionmaking.StrategyPredefined#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see xtext.decisionmaking.StrategyPredefined#getRules()
   * @see #getStrategyPredefined()
   * @generated
   */
  EReference getStrategyPredefined_Rules();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see xtext.decisionmaking.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.PredefinedRule <em>Predefined Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predefined Rule</em>'.
   * @see xtext.decisionmaking.PredefinedRule
   * @generated
   */
  EClass getPredefinedRule();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.StrategyDecisionRule <em>Strategy Decision Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Strategy Decision Rule</em>'.
   * @see xtext.decisionmaking.StrategyDecisionRule
   * @generated
   */
  EClass getStrategyDecisionRule();

  /**
   * Returns the meta object for the reference '{@link xtext.decisionmaking.StrategyDecisionRule#getDecisionrule <em>Decisionrule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Decisionrule</em>'.
   * @see xtext.decisionmaking.StrategyDecisionRule#getDecisionrule()
   * @see #getStrategyDecisionRule()
   * @generated
   */
  EReference getStrategyDecisionRule_Decisionrule();

  /**
   * Returns the meta object for the reference list '{@link xtext.decisionmaking.StrategyDecisionRule#getTeamprofiles <em>Teamprofiles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Teamprofiles</em>'.
   * @see xtext.decisionmaking.StrategyDecisionRule#getTeamprofiles()
   * @see #getStrategyDecisionRule()
   * @generated
   */
  EReference getStrategyDecisionRule_Teamprofiles();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.PredefinedDecisionRule <em>Predefined Decision Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predefined Decision Rule</em>'.
   * @see xtext.decisionmaking.PredefinedDecisionRule
   * @generated
   */
  EClass getPredefinedDecisionRule();

  /**
   * Returns the meta object for the reference '{@link xtext.decisionmaking.PredefinedDecisionRule#getDecisionrule <em>Decisionrule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Decisionrule</em>'.
   * @see xtext.decisionmaking.PredefinedDecisionRule#getDecisionrule()
   * @see #getPredefinedDecisionRule()
   * @generated
   */
  EReference getPredefinedDecisionRule_Decisionrule();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.StrategyAlgorithm <em>Strategy Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Strategy Algorithm</em>'.
   * @see xtext.decisionmaking.StrategyAlgorithm
   * @generated
   */
  EClass getStrategyAlgorithm();

  /**
   * Returns the meta object for the reference '{@link xtext.decisionmaking.StrategyAlgorithm#getAlgorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Algorithm</em>'.
   * @see xtext.decisionmaking.StrategyAlgorithm#getAlgorithm()
   * @see #getStrategyAlgorithm()
   * @generated
   */
  EReference getStrategyAlgorithm_Algorithm();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.DecisionRule <em>Decision Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decision Rule</em>'.
   * @see xtext.decisionmaking.DecisionRule
   * @generated
   */
  EClass getDecisionRule();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.DecisionRule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.decisionmaking.DecisionRule#getName()
   * @see #getDecisionRule()
   * @generated
   */
  EAttribute getDecisionRule_Name();

  /**
   * Returns the meta object for the attribute list '{@link xtext.decisionmaking.DecisionRule#getSolutionselectionaccepted <em>Solutionselectionaccepted</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Solutionselectionaccepted</em>'.
   * @see xtext.decisionmaking.DecisionRule#getSolutionselectionaccepted()
   * @see #getDecisionRule()
   * @generated
   */
  EAttribute getDecisionRule_Solutionselectionaccepted();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.DecisionRule#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see xtext.decisionmaking.DecisionRule#getDescription()
   * @see #getDecisionRule()
   * @generated
   */
  EAttribute getDecisionRule_Description();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.Algorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithm</em>'.
   * @see xtext.decisionmaking.Algorithm
   * @generated
   */
  EClass getAlgorithm();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.Algorithm#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.decisionmaking.Algorithm#getName()
   * @see #getAlgorithm()
   * @generated
   */
  EAttribute getAlgorithm_Name();

  /**
   * Returns the meta object for the attribute list '{@link xtext.decisionmaking.Algorithm#getSolutionselectionaccepted <em>Solutionselectionaccepted</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Solutionselectionaccepted</em>'.
   * @see xtext.decisionmaking.Algorithm#getSolutionselectionaccepted()
   * @see #getAlgorithm()
   * @generated
   */
  EAttribute getAlgorithm_Solutionselectionaccepted();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.Algorithm#getConsidersTP <em>Considers TP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Considers TP</em>'.
   * @see xtext.decisionmaking.Algorithm#getConsidersTP()
   * @see #getAlgorithm()
   * @generated
   */
  EAttribute getAlgorithm_ConsidersTP();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.Algorithm#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see xtext.decisionmaking.Algorithm#getDescription()
   * @see #getAlgorithm()
   * @generated
   */
  EAttribute getAlgorithm_Description();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.DesignTime <em>Design Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Design Time</em>'.
   * @see xtext.decisionmaking.DesignTime
   * @generated
   */
  EClass getDesignTime();

  /**
   * Returns the meta object for the containment reference '{@link xtext.decisionmaking.DesignTime#getDecisionsupport <em>Decisionsupport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Decisionsupport</em>'.
   * @see xtext.decisionmaking.DesignTime#getDecisionsupport()
   * @see #getDesignTime()
   * @generated
   */
  EReference getDesignTime_Decisionsupport();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.DecisionSupport <em>Decision Support</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decision Support</em>'.
   * @see xtext.decisionmaking.DecisionSupport
   * @generated
   */
  EClass getDecisionSupport();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.DecisionSupport#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.decisionmaking.DecisionSupport#getName()
   * @see #getDecisionSupport()
   * @generated
   */
  EAttribute getDecisionSupport_Name();

  /**
   * Returns the meta object for the reference list '{@link xtext.decisionmaking.DecisionSupport#getMakedecisionfor <em>Makedecisionfor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Makedecisionfor</em>'.
   * @see xtext.decisionmaking.DecisionSupport#getMakedecisionfor()
   * @see #getDecisionSupport()
   * @generated
   */
  EReference getDecisionSupport_Makedecisionfor();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.decisionmaking.DecisionSupport#getStrat <em>Strat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Strat</em>'.
   * @see xtext.decisionmaking.DecisionSupport#getStrat()
   * @see #getDecisionSupport()
   * @generated
   */
  EReference getDecisionSupport_Strat();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.Strat <em>Strat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Strat</em>'.
   * @see xtext.decisionmaking.Strat
   * @generated
   */
  EClass getStrat();

  /**
   * Returns the meta object for the reference '{@link xtext.decisionmaking.Strat#getStrat <em>Strat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Strat</em>'.
   * @see xtext.decisionmaking.Strat#getStrat()
   * @see #getStrat()
   * @generated
   */
  EReference getStrat_Strat();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.Strat#getSolutionSelectedChosen <em>Solution Selected Chosen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Solution Selected Chosen</em>'.
   * @see xtext.decisionmaking.Strat#getSolutionSelectedChosen()
   * @see #getStrat()
   * @generated
   */
  EAttribute getStrat_SolutionSelectedChosen();

  /**
   * Returns the meta object for the reference list '{@link xtext.decisionmaking.Strat#getTeamprofiles <em>Teamprofiles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Teamprofiles</em>'.
   * @see xtext.decisionmaking.Strat#getTeamprofiles()
   * @see #getStrat()
   * @generated
   */
  EReference getStrat_Teamprofiles();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.RunTime <em>Run Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Run Time</em>'.
   * @see xtext.decisionmaking.RunTime
   * @generated
   */
  EClass getRunTime();

  /**
   * Returns the meta object for the reference '{@link xtext.decisionmaking.RunTime#getDecisionsupport <em>Decisionsupport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Decisionsupport</em>'.
   * @see xtext.decisionmaking.RunTime#getDecisionsupport()
   * @see #getRunTime()
   * @generated
   */
  EReference getRunTime_Decisionsupport();

  /**
   * Returns the meta object for the reference '{@link xtext.decisionmaking.RunTime#getCategory <em>Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Category</em>'.
   * @see xtext.decisionmaking.RunTime#getCategory()
   * @see #getRunTime()
   * @generated
   */
  EReference getRunTime_Category();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.decisionmaking.RunTime#getSaddresult <em>Saddresult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Saddresult</em>'.
   * @see xtext.decisionmaking.RunTime#getSaddresult()
   * @see #getRunTime()
   * @generated
   */
  EReference getRunTime_Saddresult();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.SADDResult <em>SADD Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SADD Result</em>'.
   * @see xtext.decisionmaking.SADDResult
   * @generated
   */
  EClass getSADDResult();

  /**
   * Returns the meta object for the reference '{@link xtext.decisionmaking.SADDResult#getSadd <em>Sadd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sadd</em>'.
   * @see xtext.decisionmaking.SADDResult#getSadd()
   * @see #getSADDResult()
   * @generated
   */
  EReference getSADDResult_Sadd();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.decisionmaking.SADDResult#getAltpreferences <em>Altpreferences</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Altpreferences</em>'.
   * @see xtext.decisionmaking.SADDResult#getAltpreferences()
   * @see #getSADDResult()
   * @generated
   */
  EReference getSADDResult_Altpreferences();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.AlternativePreference <em>Alternative Preference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alternative Preference</em>'.
   * @see xtext.decisionmaking.AlternativePreference
   * @generated
   */
  EClass getAlternativePreference();

  /**
   * Returns the meta object for the reference '{@link xtext.decisionmaking.AlternativePreference#getAlternative <em>Alternative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Alternative</em>'.
   * @see xtext.decisionmaking.AlternativePreference#getAlternative()
   * @see #getAlternativePreference()
   * @generated
   */
  EReference getAlternativePreference_Alternative();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.decisionmaking.AlternativePreference#getPreferences <em>Preferences</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Preferences</em>'.
   * @see xtext.decisionmaking.AlternativePreference#getPreferences()
   * @see #getAlternativePreference()
   * @generated
   */
  EReference getAlternativePreference_Preferences();

  /**
   * Returns the meta object for class '{@link xtext.decisionmaking.Preference <em>Preference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Preference</em>'.
   * @see xtext.decisionmaking.Preference
   * @generated
   */
  EClass getPreference();

  /**
   * Returns the meta object for the reference '{@link xtext.decisionmaking.Preference#getActor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Actor</em>'.
   * @see xtext.decisionmaking.Preference#getActor()
   * @see #getPreference()
   * @generated
   */
  EReference getPreference_Actor();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.Preference#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see xtext.decisionmaking.Preference#getValue()
   * @see #getPreference()
   * @generated
   */
  EAttribute getPreference_Value();

  /**
   * Returns the meta object for the attribute '{@link xtext.decisionmaking.Preference#getRationale <em>Rationale</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rationale</em>'.
   * @see xtext.decisionmaking.Preference#getRationale()
   * @see #getPreference()
   * @generated
   */
  EAttribute getPreference_Rationale();

  /**
   * Returns the meta object for enum '{@link xtext.decisionmaking.SolutionSelectionKind <em>Solution Selection Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Solution Selection Kind</em>'.
   * @see xtext.decisionmaking.SolutionSelectionKind
   * @generated
   */
  EEnum getSolutionSelectionKind();

  /**
   * Returns the meta object for enum '{@link xtext.decisionmaking.BOOLEAN <em>BOOLEAN</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>BOOLEAN</em>'.
   * @see xtext.decisionmaking.BOOLEAN
   * @generated
   */
  EEnum getBOOLEAN();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DecisionmakingFactory getDecisionmakingFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.GroupDecisionSessionImpl <em>Group Decision Session</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.GroupDecisionSessionImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getGroupDecisionSession()
     * @generated
     */
    EClass GROUP_DECISION_SESSION = eINSTANCE.getGroupDecisionSession();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP_DECISION_SESSION__IMPORTS = eINSTANCE.getGroupDecisionSession_Imports();

    /**
     * The meta object literal for the '<em><b>Concept</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP_DECISION_SESSION__CONCEPT = eINSTANCE.getGroupDecisionSession_Concept();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.LibDesRunImpl <em>Lib Des Run</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.LibDesRunImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getLibDesRun()
     * @generated
     */
    EClass LIB_DES_RUN = eINSTANCE.getLibDesRun();

    /**
     * The meta object literal for the '<em><b>Library</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIB_DES_RUN__LIBRARY = eINSTANCE.getLibDesRun_Library();

    /**
     * The meta object literal for the '<em><b>Designtime</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIB_DES_RUN__DESIGNTIME = eINSTANCE.getLibDesRun_Designtime();

    /**
     * The meta object literal for the '<em><b>Runtime</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIB_DES_RUN__RUNTIME = eINSTANCE.getLibDesRun_Runtime();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.ImportImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORT_URI = eINSTANCE.getImport_ImportURI();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.LibraryImpl <em>Library</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.LibraryImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getLibrary()
     * @generated
     */
    EClass LIBRARY = eINSTANCE.getLibrary();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIBRARY__NAME = eINSTANCE.getLibrary_Name();

    /**
     * The meta object literal for the '<em><b>Decisionrules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIBRARY__DECISIONRULES = eINSTANCE.getLibrary_Decisionrules();

    /**
     * The meta object literal for the '<em><b>Algorithms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIBRARY__ALGORITHMS = eINSTANCE.getLibrary_Algorithms();

    /**
     * The meta object literal for the '<em><b>Strategies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIBRARY__STRATEGIES = eINSTANCE.getLibrary_Strategies();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.StrategyImpl <em>Strategy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.StrategyImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getStrategy()
     * @generated
     */
    EClass STRATEGY = eINSTANCE.getStrategy();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRATEGY__NAME = eINSTANCE.getStrategy_Name();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRATEGY__RULES = eINSTANCE.getStrategy_Rules();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.StrategyPredefinedImpl <em>Strategy Predefined</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.StrategyPredefinedImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getStrategyPredefined()
     * @generated
     */
    EClass STRATEGY_PREDEFINED = eINSTANCE.getStrategyPredefined();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRATEGY_PREDEFINED__NAME = eINSTANCE.getStrategyPredefined_Name();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRATEGY_PREDEFINED__RULES = eINSTANCE.getStrategyPredefined_Rules();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.RuleImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.PredefinedRuleImpl <em>Predefined Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.PredefinedRuleImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getPredefinedRule()
     * @generated
     */
    EClass PREDEFINED_RULE = eINSTANCE.getPredefinedRule();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.StrategyDecisionRuleImpl <em>Strategy Decision Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.StrategyDecisionRuleImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getStrategyDecisionRule()
     * @generated
     */
    EClass STRATEGY_DECISION_RULE = eINSTANCE.getStrategyDecisionRule();

    /**
     * The meta object literal for the '<em><b>Decisionrule</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRATEGY_DECISION_RULE__DECISIONRULE = eINSTANCE.getStrategyDecisionRule_Decisionrule();

    /**
     * The meta object literal for the '<em><b>Teamprofiles</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRATEGY_DECISION_RULE__TEAMPROFILES = eINSTANCE.getStrategyDecisionRule_Teamprofiles();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.PredefinedDecisionRuleImpl <em>Predefined Decision Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.PredefinedDecisionRuleImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getPredefinedDecisionRule()
     * @generated
     */
    EClass PREDEFINED_DECISION_RULE = eINSTANCE.getPredefinedDecisionRule();

    /**
     * The meta object literal for the '<em><b>Decisionrule</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDEFINED_DECISION_RULE__DECISIONRULE = eINSTANCE.getPredefinedDecisionRule_Decisionrule();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.StrategyAlgorithmImpl <em>Strategy Algorithm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.StrategyAlgorithmImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getStrategyAlgorithm()
     * @generated
     */
    EClass STRATEGY_ALGORITHM = eINSTANCE.getStrategyAlgorithm();

    /**
     * The meta object literal for the '<em><b>Algorithm</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRATEGY_ALGORITHM__ALGORITHM = eINSTANCE.getStrategyAlgorithm_Algorithm();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.DecisionRuleImpl <em>Decision Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.DecisionRuleImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getDecisionRule()
     * @generated
     */
    EClass DECISION_RULE = eINSTANCE.getDecisionRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_RULE__NAME = eINSTANCE.getDecisionRule_Name();

    /**
     * The meta object literal for the '<em><b>Solutionselectionaccepted</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_RULE__SOLUTIONSELECTIONACCEPTED = eINSTANCE.getDecisionRule_Solutionselectionaccepted();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_RULE__DESCRIPTION = eINSTANCE.getDecisionRule_Description();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.AlgorithmImpl <em>Algorithm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.AlgorithmImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getAlgorithm()
     * @generated
     */
    EClass ALGORITHM = eINSTANCE.getAlgorithm();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM__NAME = eINSTANCE.getAlgorithm_Name();

    /**
     * The meta object literal for the '<em><b>Solutionselectionaccepted</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM__SOLUTIONSELECTIONACCEPTED = eINSTANCE.getAlgorithm_Solutionselectionaccepted();

    /**
     * The meta object literal for the '<em><b>Considers TP</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM__CONSIDERS_TP = eINSTANCE.getAlgorithm_ConsidersTP();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM__DESCRIPTION = eINSTANCE.getAlgorithm_Description();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.DesignTimeImpl <em>Design Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.DesignTimeImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getDesignTime()
     * @generated
     */
    EClass DESIGN_TIME = eINSTANCE.getDesignTime();

    /**
     * The meta object literal for the '<em><b>Decisionsupport</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESIGN_TIME__DECISIONSUPPORT = eINSTANCE.getDesignTime_Decisionsupport();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.DecisionSupportImpl <em>Decision Support</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.DecisionSupportImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getDecisionSupport()
     * @generated
     */
    EClass DECISION_SUPPORT = eINSTANCE.getDecisionSupport();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_SUPPORT__NAME = eINSTANCE.getDecisionSupport_Name();

    /**
     * The meta object literal for the '<em><b>Makedecisionfor</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECISION_SUPPORT__MAKEDECISIONFOR = eINSTANCE.getDecisionSupport_Makedecisionfor();

    /**
     * The meta object literal for the '<em><b>Strat</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECISION_SUPPORT__STRAT = eINSTANCE.getDecisionSupport_Strat();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.StratImpl <em>Strat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.StratImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getStrat()
     * @generated
     */
    EClass STRAT = eINSTANCE.getStrat();

    /**
     * The meta object literal for the '<em><b>Strat</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRAT__STRAT = eINSTANCE.getStrat_Strat();

    /**
     * The meta object literal for the '<em><b>Solution Selected Chosen</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRAT__SOLUTION_SELECTED_CHOSEN = eINSTANCE.getStrat_SolutionSelectedChosen();

    /**
     * The meta object literal for the '<em><b>Teamprofiles</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRAT__TEAMPROFILES = eINSTANCE.getStrat_Teamprofiles();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.RunTimeImpl <em>Run Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.RunTimeImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getRunTime()
     * @generated
     */
    EClass RUN_TIME = eINSTANCE.getRunTime();

    /**
     * The meta object literal for the '<em><b>Decisionsupport</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RUN_TIME__DECISIONSUPPORT = eINSTANCE.getRunTime_Decisionsupport();

    /**
     * The meta object literal for the '<em><b>Category</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RUN_TIME__CATEGORY = eINSTANCE.getRunTime_Category();

    /**
     * The meta object literal for the '<em><b>Saddresult</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RUN_TIME__SADDRESULT = eINSTANCE.getRunTime_Saddresult();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.SADDResultImpl <em>SADD Result</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.SADDResultImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getSADDResult()
     * @generated
     */
    EClass SADD_RESULT = eINSTANCE.getSADDResult();

    /**
     * The meta object literal for the '<em><b>Sadd</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SADD_RESULT__SADD = eINSTANCE.getSADDResult_Sadd();

    /**
     * The meta object literal for the '<em><b>Altpreferences</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SADD_RESULT__ALTPREFERENCES = eINSTANCE.getSADDResult_Altpreferences();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.AlternativePreferenceImpl <em>Alternative Preference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.AlternativePreferenceImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getAlternativePreference()
     * @generated
     */
    EClass ALTERNATIVE_PREFERENCE = eINSTANCE.getAlternativePreference();

    /**
     * The meta object literal for the '<em><b>Alternative</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALTERNATIVE_PREFERENCE__ALTERNATIVE = eINSTANCE.getAlternativePreference_Alternative();

    /**
     * The meta object literal for the '<em><b>Preferences</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALTERNATIVE_PREFERENCE__PREFERENCES = eINSTANCE.getAlternativePreference_Preferences();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.impl.PreferenceImpl <em>Preference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.impl.PreferenceImpl
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getPreference()
     * @generated
     */
    EClass PREFERENCE = eINSTANCE.getPreference();

    /**
     * The meta object literal for the '<em><b>Actor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREFERENCE__ACTOR = eINSTANCE.getPreference_Actor();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREFERENCE__VALUE = eINSTANCE.getPreference_Value();

    /**
     * The meta object literal for the '<em><b>Rationale</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREFERENCE__RATIONALE = eINSTANCE.getPreference_Rationale();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.SolutionSelectionKind <em>Solution Selection Kind</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.SolutionSelectionKind
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getSolutionSelectionKind()
     * @generated
     */
    EEnum SOLUTION_SELECTION_KIND = eINSTANCE.getSolutionSelectionKind();

    /**
     * The meta object literal for the '{@link xtext.decisionmaking.BOOLEAN <em>BOOLEAN</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.decisionmaking.BOOLEAN
     * @see xtext.decisionmaking.impl.DecisionmakingPackageImpl#getBOOLEAN()
     * @generated
     */
    EEnum BOOLEAN = eINSTANCE.getBOOLEAN();

  }

} //DecisionmakingPackage
