/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decision Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.DecisionRule#getName <em>Name</em>}</li>
 *   <li>{@link xtext.decisionmaking.DecisionRule#getPrefIndAccepted <em>Pref Ind Accepted</em>}</li>
 *   <li>{@link xtext.decisionmaking.DecisionRule#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see xtext.decisionmaking.DecisionmakingPackage#getDecisionRule()
 * @model
 * @generated
 */
public interface DecisionRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.decisionmaking.DecisionmakingPackage#getDecisionRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.DecisionRule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Pref Ind Accepted</b></em>' attribute list.
   * The list contents are of type {@link xtext.decisionmaking.PreferenceIndicationKind}.
   * The literals are from the enumeration {@link xtext.decisionmaking.PreferenceIndicationKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pref Ind Accepted</em>' attribute list.
   * @see xtext.decisionmaking.PreferenceIndicationKind
   * @see xtext.decisionmaking.DecisionmakingPackage#getDecisionRule_PrefIndAccepted()
   * @model unique="false"
   * @generated
   */
  EList<PreferenceIndicationKind> getPrefIndAccepted();

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see xtext.decisionmaking.DecisionmakingPackage#getDecisionRule_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.DecisionRule#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // DecisionRule
