/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Library</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.Library#getName <em>Name</em>}</li>
 *   <li>{@link xtext.decisionmaking.Library#getDecisionrules <em>Decisionrules</em>}</li>
 *   <li>{@link xtext.decisionmaking.Library#getAlgorithms <em>Algorithms</em>}</li>
 *   <li>{@link xtext.decisionmaking.Library#getStrategies <em>Strategies</em>}</li>
 * </ul>
 *
 * @see xtext.decisionmaking.DecisionmakingPackage#getLibrary()
 * @model
 * @generated
 */
public interface Library extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.decisionmaking.DecisionmakingPackage#getLibrary_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.Library#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Decisionrules</b></em>' containment reference list.
   * The list contents are of type {@link xtext.decisionmaking.DecisionRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decisionrules</em>' containment reference list.
   * @see xtext.decisionmaking.DecisionmakingPackage#getLibrary_Decisionrules()
   * @model containment="true"
   * @generated
   */
  EList<DecisionRule> getDecisionrules();

  /**
   * Returns the value of the '<em><b>Algorithms</b></em>' containment reference list.
   * The list contents are of type {@link xtext.decisionmaking.Algorithm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algorithms</em>' containment reference list.
   * @see xtext.decisionmaking.DecisionmakingPackage#getLibrary_Algorithms()
   * @model containment="true"
   * @generated
   */
  EList<Algorithm> getAlgorithms();

  /**
   * Returns the value of the '<em><b>Strategies</b></em>' containment reference list.
   * The list contents are of type {@link xtext.decisionmaking.StrategyPredefined}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strategies</em>' containment reference list.
   * @see xtext.decisionmaking.DecisionmakingPackage#getLibrary_Strategies()
   * @model containment="true"
   * @generated
   */
  EList<StrategyPredefined> getStrategies();

} // Library
