/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Preference Indication Kind</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see xtext.decisionmaking.DecisionmakingPackage#getPreferenceIndicationKind()
 * @model
 * @generated
 */
public enum PreferenceIndicationKind implements Enumerator
{
  /**
   * The '<em><b>Ranking</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RANKING_VALUE
   * @generated
   * @ordered
   */
  RANKING(0, "ranking", "Ranking"),

  /**
   * The '<em><b>Rating</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RATING_VALUE
   * @generated
   * @ordered
   */
  RATING(1, "rating", "Rating"),

  /**
   * The '<em><b>Yesno</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #YESNO_VALUE
   * @generated
   * @ordered
   */
  YESNO(2, "yesno", "YesNo");

  /**
   * The '<em><b>Ranking</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RANKING
   * @model name="ranking" literal="Ranking"
   * @generated
   * @ordered
   */
  public static final int RANKING_VALUE = 0;

  /**
   * The '<em><b>Rating</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RATING
   * @model name="rating" literal="Rating"
   * @generated
   * @ordered
   */
  public static final int RATING_VALUE = 1;

  /**
   * The '<em><b>Yesno</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #YESNO
   * @model name="yesno" literal="YesNo"
   * @generated
   * @ordered
   */
  public static final int YESNO_VALUE = 2;

  /**
   * An array of all the '<em><b>Preference Indication Kind</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final PreferenceIndicationKind[] VALUES_ARRAY =
    new PreferenceIndicationKind[]
    {
      RANKING,
      RATING,
      YESNO,
    };

  /**
   * A public read-only list of all the '<em><b>Preference Indication Kind</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<PreferenceIndicationKind> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Preference Indication Kind</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PreferenceIndicationKind get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      PreferenceIndicationKind result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Preference Indication Kind</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PreferenceIndicationKind getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      PreferenceIndicationKind result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Preference Indication Kind</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PreferenceIndicationKind get(int value)
  {
    switch (value)
    {
      case RANKING_VALUE: return RANKING;
      case RATING_VALUE: return RATING;
      case YESNO_VALUE: return YESNO;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private PreferenceIndicationKind(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //PreferenceIndicationKind
