/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import org.eclipse.emf.ecore.EObject;

import xtext.teamprofile.Actor;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Preference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.Preference#getActor <em>Actor</em>}</li>
 *   <li>{@link xtext.decisionmaking.Preference#getValue <em>Value</em>}</li>
 *   <li>{@link xtext.decisionmaking.Preference#getRationale <em>Rationale</em>}</li>
 * </ul>
 *
 * @see xtext.decisionmaking.DecisionmakingPackage#getPreference()
 * @model
 * @generated
 */
public interface Preference extends EObject
{
  /**
   * Returns the value of the '<em><b>Actor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actor</em>' reference.
   * @see #setActor(Actor)
   * @see xtext.decisionmaking.DecisionmakingPackage#getPreference_Actor()
   * @model
   * @generated
   */
  Actor getActor();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.Preference#getActor <em>Actor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actor</em>' reference.
   * @see #getActor()
   * @generated
   */
  void setActor(Actor value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see xtext.decisionmaking.DecisionmakingPackage#getPreference_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.Preference#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Rationale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rationale</em>' attribute.
   * @see #setRationale(String)
   * @see xtext.decisionmaking.DecisionmakingPackage#getPreference_Rationale()
   * @model
   * @generated
   */
  String getRationale();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.Preference#getRationale <em>Rationale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rationale</em>' attribute.
   * @see #getRationale()
   * @generated
   */
  void setRationale(String value);

} // Preference
