/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.decisionmaking.DecisionmakingPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
} // Rule
