/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import xtext.sadd.Category;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Run Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.RunTime#getDecisionsupport <em>Decisionsupport</em>}</li>
 *   <li>{@link xtext.decisionmaking.RunTime#getCategory <em>Category</em>}</li>
 *   <li>{@link xtext.decisionmaking.RunTime#getSaddresult <em>Saddresult</em>}</li>
 * </ul>
 *
 * @see xtext.decisionmaking.DecisionmakingPackage#getRunTime()
 * @model
 * @generated
 */
public interface RunTime extends EObject
{
  /**
   * Returns the value of the '<em><b>Decisionsupport</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decisionsupport</em>' reference.
   * @see #setDecisionsupport(DecisionSupport)
   * @see xtext.decisionmaking.DecisionmakingPackage#getRunTime_Decisionsupport()
   * @model
   * @generated
   */
  DecisionSupport getDecisionsupport();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.RunTime#getDecisionsupport <em>Decisionsupport</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decisionsupport</em>' reference.
   * @see #getDecisionsupport()
   * @generated
   */
  void setDecisionsupport(DecisionSupport value);

  /**
   * Returns the value of the '<em><b>Category</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Category</em>' reference.
   * @see #setCategory(Category)
   * @see xtext.decisionmaking.DecisionmakingPackage#getRunTime_Category()
   * @model
   * @generated
   */
  Category getCategory();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.RunTime#getCategory <em>Category</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Category</em>' reference.
   * @see #getCategory()
   * @generated
   */
  void setCategory(Category value);

  /**
   * Returns the value of the '<em><b>Saddresult</b></em>' containment reference list.
   * The list contents are of type {@link xtext.decisionmaking.SADDResult}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Saddresult</em>' containment reference list.
   * @see xtext.decisionmaking.DecisionmakingPackage#getRunTime_Saddresult()
   * @model containment="true"
   * @generated
   */
  EList<SADDResult> getSaddresult();

} // RunTime
