/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;

import org.eclipse.emf.common.util.EList;

import xtext.teamprofile.Profile;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Strategy Decision Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.StrategyDecisionRule#getDecisionrule <em>Decisionrule</em>}</li>
 *   <li>{@link xtext.decisionmaking.StrategyDecisionRule#getTeamprofiles <em>Teamprofiles</em>}</li>
 * </ul>
 *
 * @see xtext.decisionmaking.DecisionmakingPackage#getStrategyDecisionRule()
 * @model
 * @generated
 */
public interface StrategyDecisionRule extends Rule
{
  /**
   * Returns the value of the '<em><b>Decisionrule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decisionrule</em>' reference.
   * @see #setDecisionrule(DecisionRule)
   * @see xtext.decisionmaking.DecisionmakingPackage#getStrategyDecisionRule_Decisionrule()
   * @model
   * @generated
   */
  DecisionRule getDecisionrule();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.StrategyDecisionRule#getDecisionrule <em>Decisionrule</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decisionrule</em>' reference.
   * @see #getDecisionrule()
   * @generated
   */
  void setDecisionrule(DecisionRule value);

  /**
   * Returns the value of the '<em><b>Teamprofiles</b></em>' reference list.
   * The list contents are of type {@link xtext.teamprofile.Profile}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Teamprofiles</em>' reference list.
   * @see xtext.decisionmaking.DecisionmakingPackage#getStrategyDecisionRule_Teamprofiles()
   * @model
   * @generated
   */
  EList<Profile> getTeamprofiles();

} // StrategyDecisionRule
