/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Strategy Algorithm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.StrategyAlgorithm#getAlgorithm <em>Algorithm</em>}</li>
 * </ul>
 *
 * @see xtext.decisionmaking.DecisionmakingPackage#getStrategyAlgorithm()
 * @model
 * @generated
 */
public interface StrategyAlgorithm extends Rule, PredefinedRule
{
  /**
   * Returns the value of the '<em><b>Algorithm</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algorithm</em>' reference.
   * @see #setAlgorithm(Algorithm)
   * @see xtext.decisionmaking.DecisionmakingPackage#getStrategyAlgorithm_Algorithm()
   * @model
   * @generated
   */
  Algorithm getAlgorithm();

  /**
   * Sets the value of the '{@link xtext.decisionmaking.StrategyAlgorithm#getAlgorithm <em>Algorithm</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Algorithm</em>' reference.
   * @see #getAlgorithm()
   * @generated
   */
  void setAlgorithm(Algorithm value);

} // StrategyAlgorithm
