/**
 * generated by Xtext 2.35.0
 */
package xtext.teamprofile.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.teamprofile.Attribute;
import xtext.teamprofile.TeamprofilePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.teamprofile.impl.AttributeImpl#getHfproperty <em>Hfproperty</em>}</li>
 *   <li>{@link xtext.teamprofile.impl.AttributeImpl#getHfmeasurementvalue <em>Hfmeasurementvalue</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeImpl extends MinimalEObjectImpl.Container implements Attribute
{
  /**
   * The default value of the '{@link #getHfproperty() <em>Hfproperty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHfproperty()
   * @generated
   * @ordered
   */
  protected static final String HFPROPERTY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHfproperty() <em>Hfproperty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHfproperty()
   * @generated
   * @ordered
   */
  protected String hfproperty = HFPROPERTY_EDEFAULT;

  /**
   * The default value of the '{@link #getHfmeasurementvalue() <em>Hfmeasurementvalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHfmeasurementvalue()
   * @generated
   * @ordered
   */
  protected static final String HFMEASUREMENTVALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHfmeasurementvalue() <em>Hfmeasurementvalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHfmeasurementvalue()
   * @generated
   * @ordered
   */
  protected String hfmeasurementvalue = HFMEASUREMENTVALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TeamprofilePackage.Literals.ATTRIBUTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHfproperty()
  {
    return hfproperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHfproperty(String newHfproperty)
  {
    String oldHfproperty = hfproperty;
    hfproperty = newHfproperty;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TeamprofilePackage.ATTRIBUTE__HFPROPERTY, oldHfproperty, hfproperty));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHfmeasurementvalue()
  {
    return hfmeasurementvalue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHfmeasurementvalue(String newHfmeasurementvalue)
  {
    String oldHfmeasurementvalue = hfmeasurementvalue;
    hfmeasurementvalue = newHfmeasurementvalue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TeamprofilePackage.ATTRIBUTE__HFMEASUREMENTVALUE, oldHfmeasurementvalue, hfmeasurementvalue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TeamprofilePackage.ATTRIBUTE__HFPROPERTY:
        return getHfproperty();
      case TeamprofilePackage.ATTRIBUTE__HFMEASUREMENTVALUE:
        return getHfmeasurementvalue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TeamprofilePackage.ATTRIBUTE__HFPROPERTY:
        setHfproperty((String)newValue);
        return;
      case TeamprofilePackage.ATTRIBUTE__HFMEASUREMENTVALUE:
        setHfmeasurementvalue((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TeamprofilePackage.ATTRIBUTE__HFPROPERTY:
        setHfproperty(HFPROPERTY_EDEFAULT);
        return;
      case TeamprofilePackage.ATTRIBUTE__HFMEASUREMENTVALUE:
        setHfmeasurementvalue(HFMEASUREMENTVALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TeamprofilePackage.ATTRIBUTE__HFPROPERTY:
        return HFPROPERTY_EDEFAULT == null ? hfproperty != null : !HFPROPERTY_EDEFAULT.equals(hfproperty);
      case TeamprofilePackage.ATTRIBUTE__HFMEASUREMENTVALUE:
        return HFMEASUREMENTVALUE_EDEFAULT == null ? hfmeasurementvalue != null : !HFMEASUREMENTVALUE_EDEFAULT.equals(hfmeasurementvalue);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (hfproperty: ");
    result.append(hfproperty);
    result.append(", hfmeasurementvalue: ");
    result.append(hfmeasurementvalue);
    result.append(')');
    return result.toString();
  }

} //AttributeImpl
