/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import xtext.decisionmaking.AlternativePreference;
import xtext.decisionmaking.DecisionmakingPackage;
import xtext.decisionmaking.Preference;

import xtext.sadd.Alternative;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Alternative Preference</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.impl.AlternativePreferenceImpl#getAlternative <em>Alternative</em>}</li>
 *   <li>{@link xtext.decisionmaking.impl.AlternativePreferenceImpl#getPreferences <em>Preferences</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AlternativePreferenceImpl extends MinimalEObjectImpl.Container implements AlternativePreference
{
  /**
   * The cached value of the '{@link #getAlternative() <em>Alternative</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlternative()
   * @generated
   * @ordered
   */
  protected Alternative alternative;

  /**
   * The cached value of the '{@link #getPreferences() <em>Preferences</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPreferences()
   * @generated
   * @ordered
   */
  protected EList<Preference> preferences;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AlternativePreferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DecisionmakingPackage.Literals.ALTERNATIVE_PREFERENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Alternative getAlternative()
  {
    if (alternative != null && alternative.eIsProxy())
    {
      InternalEObject oldAlternative = (InternalEObject)alternative;
      alternative = (Alternative)eResolveProxy(oldAlternative);
      if (alternative != oldAlternative)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DecisionmakingPackage.ALTERNATIVE_PREFERENCE__ALTERNATIVE, oldAlternative, alternative));
      }
    }
    return alternative;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Alternative basicGetAlternative()
  {
    return alternative;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlternative(Alternative newAlternative)
  {
    Alternative oldAlternative = alternative;
    alternative = newAlternative;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DecisionmakingPackage.ALTERNATIVE_PREFERENCE__ALTERNATIVE, oldAlternative, alternative));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Preference> getPreferences()
  {
    if (preferences == null)
    {
      preferences = new EObjectContainmentEList<Preference>(Preference.class, this, DecisionmakingPackage.ALTERNATIVE_PREFERENCE__PREFERENCES);
    }
    return preferences;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.ALTERNATIVE_PREFERENCE__PREFERENCES:
        return ((InternalEList<?>)getPreferences()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.ALTERNATIVE_PREFERENCE__ALTERNATIVE:
        if (resolve) return getAlternative();
        return basicGetAlternative();
      case DecisionmakingPackage.ALTERNATIVE_PREFERENCE__PREFERENCES:
        return getPreferences();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.ALTERNATIVE_PREFERENCE__ALTERNATIVE:
        setAlternative((Alternative)newValue);
        return;
      case DecisionmakingPackage.ALTERNATIVE_PREFERENCE__PREFERENCES:
        getPreferences().clear();
        getPreferences().addAll((Collection<? extends Preference>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.ALTERNATIVE_PREFERENCE__ALTERNATIVE:
        setAlternative((Alternative)null);
        return;
      case DecisionmakingPackage.ALTERNATIVE_PREFERENCE__PREFERENCES:
        getPreferences().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.ALTERNATIVE_PREFERENCE__ALTERNATIVE:
        return alternative != null;
      case DecisionmakingPackage.ALTERNATIVE_PREFERENCE__PREFERENCES:
        return preferences != null && !preferences.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AlternativePreferenceImpl
