/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import xtext.decisionmaking.DecisionSupport;
import xtext.decisionmaking.DecisionmakingPackage;
import xtext.decisionmaking.Strat;

import xtext.sadd.Category;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Decision Support</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.impl.DecisionSupportImpl#getName <em>Name</em>}</li>
 *   <li>{@link xtext.decisionmaking.impl.DecisionSupportImpl#getMakedecisionfor <em>Makedecisionfor</em>}</li>
 *   <li>{@link xtext.decisionmaking.impl.DecisionSupportImpl#getStrat <em>Strat</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DecisionSupportImpl extends MinimalEObjectImpl.Container implements DecisionSupport
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getMakedecisionfor() <em>Makedecisionfor</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMakedecisionfor()
   * @generated
   * @ordered
   */
  protected EList<Category> makedecisionfor;

  /**
   * The cached value of the '{@link #getStrat() <em>Strat</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStrat()
   * @generated
   * @ordered
   */
  protected EList<Strat> strat;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DecisionSupportImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DecisionmakingPackage.Literals.DECISION_SUPPORT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DecisionmakingPackage.DECISION_SUPPORT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Category> getMakedecisionfor()
  {
    if (makedecisionfor == null)
    {
      makedecisionfor = new EObjectResolvingEList<Category>(Category.class, this, DecisionmakingPackage.DECISION_SUPPORT__MAKEDECISIONFOR);
    }
    return makedecisionfor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Strat> getStrat()
  {
    if (strat == null)
    {
      strat = new EObjectContainmentEList<Strat>(Strat.class, this, DecisionmakingPackage.DECISION_SUPPORT__STRAT);
    }
    return strat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.DECISION_SUPPORT__STRAT:
        return ((InternalEList<?>)getStrat()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.DECISION_SUPPORT__NAME:
        return getName();
      case DecisionmakingPackage.DECISION_SUPPORT__MAKEDECISIONFOR:
        return getMakedecisionfor();
      case DecisionmakingPackage.DECISION_SUPPORT__STRAT:
        return getStrat();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.DECISION_SUPPORT__NAME:
        setName((String)newValue);
        return;
      case DecisionmakingPackage.DECISION_SUPPORT__MAKEDECISIONFOR:
        getMakedecisionfor().clear();
        getMakedecisionfor().addAll((Collection<? extends Category>)newValue);
        return;
      case DecisionmakingPackage.DECISION_SUPPORT__STRAT:
        getStrat().clear();
        getStrat().addAll((Collection<? extends Strat>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.DECISION_SUPPORT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DecisionmakingPackage.DECISION_SUPPORT__MAKEDECISIONFOR:
        getMakedecisionfor().clear();
        return;
      case DecisionmakingPackage.DECISION_SUPPORT__STRAT:
        getStrat().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.DECISION_SUPPORT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DecisionmakingPackage.DECISION_SUPPORT__MAKEDECISIONFOR:
        return makedecisionfor != null && !makedecisionfor.isEmpty();
      case DecisionmakingPackage.DECISION_SUPPORT__STRAT:
        return strat != null && !strat.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //DecisionSupportImpl
