/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import xtext.decisionmaking.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DecisionmakingFactoryImpl extends EFactoryImpl implements DecisionmakingFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static DecisionmakingFactory init()
  {
    try
    {
      DecisionmakingFactory theDecisionmakingFactory = (DecisionmakingFactory)EPackage.Registry.INSTANCE.getEFactory(DecisionmakingPackage.eNS_URI);
      if (theDecisionmakingFactory != null)
      {
        return theDecisionmakingFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new DecisionmakingFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DecisionmakingFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case DecisionmakingPackage.GROUP_DECISION_SESSION: return createGroupDecisionSession();
      case DecisionmakingPackage.LIB_DES_RUN: return createLibDesRun();
      case DecisionmakingPackage.IMPORT: return createImport();
      case DecisionmakingPackage.LIBRARY: return createLibrary();
      case DecisionmakingPackage.STRATEGY: return createStrategy();
      case DecisionmakingPackage.STRATEGY_PREDEFINED: return createStrategyPredefined();
      case DecisionmakingPackage.RULE: return createRule();
      case DecisionmakingPackage.PREDEFINED_RULE: return createPredefinedRule();
      case DecisionmakingPackage.STRATEGY_DECISION_RULE: return createStrategyDecisionRule();
      case DecisionmakingPackage.PREDEFINED_DECISION_RULE: return createPredefinedDecisionRule();
      case DecisionmakingPackage.STRATEGY_ALGORITHM: return createStrategyAlgorithm();
      case DecisionmakingPackage.DECISION_RULE: return createDecisionRule();
      case DecisionmakingPackage.ALGORITHM: return createAlgorithm();
      case DecisionmakingPackage.DESIGN_TIME: return createDesignTime();
      case DecisionmakingPackage.DECISION_SUPPORT: return createDecisionSupport();
      case DecisionmakingPackage.STRAT: return createStrat();
      case DecisionmakingPackage.RUN_TIME: return createRunTime();
      case DecisionmakingPackage.SADD_RESULT: return createSADDResult();
      case DecisionmakingPackage.ALTERNATIVE_PREFERENCE: return createAlternativePreference();
      case DecisionmakingPackage.PREFERENCE: return createPreference();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case DecisionmakingPackage.PREFERENCE_INDICATION_KIND:
        return createPreferenceIndicationKindFromString(eDataType, initialValue);
      case DecisionmakingPackage.BOOLEAN:
        return createBOOLEANFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case DecisionmakingPackage.PREFERENCE_INDICATION_KIND:
        return convertPreferenceIndicationKindToString(eDataType, instanceValue);
      case DecisionmakingPackage.BOOLEAN:
        return convertBOOLEANToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GroupDecisionSession createGroupDecisionSession()
  {
    GroupDecisionSessionImpl groupDecisionSession = new GroupDecisionSessionImpl();
    return groupDecisionSession;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LibDesRun createLibDesRun()
  {
    LibDesRunImpl libDesRun = new LibDesRunImpl();
    return libDesRun;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Library createLibrary()
  {
    LibraryImpl library = new LibraryImpl();
    return library;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Strategy createStrategy()
  {
    StrategyImpl strategy = new StrategyImpl();
    return strategy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StrategyPredefined createStrategyPredefined()
  {
    StrategyPredefinedImpl strategyPredefined = new StrategyPredefinedImpl();
    return strategyPredefined;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rule createRule()
  {
    RuleImpl rule = new RuleImpl();
    return rule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredefinedRule createPredefinedRule()
  {
    PredefinedRuleImpl predefinedRule = new PredefinedRuleImpl();
    return predefinedRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StrategyDecisionRule createStrategyDecisionRule()
  {
    StrategyDecisionRuleImpl strategyDecisionRule = new StrategyDecisionRuleImpl();
    return strategyDecisionRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredefinedDecisionRule createPredefinedDecisionRule()
  {
    PredefinedDecisionRuleImpl predefinedDecisionRule = new PredefinedDecisionRuleImpl();
    return predefinedDecisionRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StrategyAlgorithm createStrategyAlgorithm()
  {
    StrategyAlgorithmImpl strategyAlgorithm = new StrategyAlgorithmImpl();
    return strategyAlgorithm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DecisionRule createDecisionRule()
  {
    DecisionRuleImpl decisionRule = new DecisionRuleImpl();
    return decisionRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Algorithm createAlgorithm()
  {
    AlgorithmImpl algorithm = new AlgorithmImpl();
    return algorithm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DesignTime createDesignTime()
  {
    DesignTimeImpl designTime = new DesignTimeImpl();
    return designTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DecisionSupport createDecisionSupport()
  {
    DecisionSupportImpl decisionSupport = new DecisionSupportImpl();
    return decisionSupport;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Strat createStrat()
  {
    StratImpl strat = new StratImpl();
    return strat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RunTime createRunTime()
  {
    RunTimeImpl runTime = new RunTimeImpl();
    return runTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SADDResult createSADDResult()
  {
    SADDResultImpl saddResult = new SADDResultImpl();
    return saddResult;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AlternativePreference createAlternativePreference()
  {
    AlternativePreferenceImpl alternativePreference = new AlternativePreferenceImpl();
    return alternativePreference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Preference createPreference()
  {
    PreferenceImpl preference = new PreferenceImpl();
    return preference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PreferenceIndicationKind createPreferenceIndicationKindFromString(EDataType eDataType, String initialValue)
  {
    PreferenceIndicationKind result = PreferenceIndicationKind.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertPreferenceIndicationKindToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BOOLEAN createBOOLEANFromString(EDataType eDataType, String initialValue)
  {
    BOOLEAN result = BOOLEAN.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertBOOLEANToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DecisionmakingPackage getDecisionmakingPackage()
  {
    return (DecisionmakingPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static DecisionmakingPackage getPackage()
  {
    return DecisionmakingPackage.eINSTANCE;
  }

} //DecisionmakingFactoryImpl
