/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import xtext.decisionmaking.Algorithm;
import xtext.decisionmaking.AlternativePreference;
import xtext.decisionmaking.DecisionRule;
import xtext.decisionmaking.DecisionSupport;
import xtext.decisionmaking.DecisionmakingFactory;
import xtext.decisionmaking.DecisionmakingPackage;
import xtext.decisionmaking.DesignTime;
import xtext.decisionmaking.GroupDecisionSession;
import xtext.decisionmaking.Import;
import xtext.decisionmaking.LibDesRun;
import xtext.decisionmaking.Library;
import xtext.decisionmaking.PredefinedDecisionRule;
import xtext.decisionmaking.PredefinedRule;
import xtext.decisionmaking.Preference;
import xtext.decisionmaking.PreferenceIndicationKind;
import xtext.decisionmaking.Rule;
import xtext.decisionmaking.RunTime;
import xtext.decisionmaking.SADDResult;
import xtext.decisionmaking.Strat;
import xtext.decisionmaking.Strategy;
import xtext.decisionmaking.StrategyAlgorithm;
import xtext.decisionmaking.StrategyDecisionRule;
import xtext.decisionmaking.StrategyPredefined;

import xtext.sadd.SaddPackage;

import xtext.teamprofile.TeamprofilePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DecisionmakingPackageImpl extends EPackageImpl implements DecisionmakingPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass groupDecisionSessionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass libDesRunEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass importEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass libraryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass strategyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass strategyPredefinedEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ruleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass predefinedRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass strategyDecisionRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass predefinedDecisionRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass strategyAlgorithmEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass decisionRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass algorithmEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass designTimeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass decisionSupportEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stratEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass runTimeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass saddResultEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass alternativePreferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass preferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum preferenceIndicationKindEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum booleanEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see xtext.decisionmaking.DecisionmakingPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private DecisionmakingPackageImpl()
  {
    super(eNS_URI, DecisionmakingFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link DecisionmakingPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static DecisionmakingPackage init()
  {
    if (isInited) return (DecisionmakingPackage)EPackage.Registry.INSTANCE.getEPackage(DecisionmakingPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredDecisionmakingPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    DecisionmakingPackageImpl theDecisionmakingPackage = registeredDecisionmakingPackage instanceof DecisionmakingPackageImpl ? (DecisionmakingPackageImpl)registeredDecisionmakingPackage : new DecisionmakingPackageImpl();

    isInited = true;

    // Initialize simple dependencies
    SaddPackage.eINSTANCE.eClass();
    TeamprofilePackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theDecisionmakingPackage.createPackageContents();

    // Initialize created meta-data
    theDecisionmakingPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theDecisionmakingPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(DecisionmakingPackage.eNS_URI, theDecisionmakingPackage);
    return theDecisionmakingPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGroupDecisionSession()
  {
    return groupDecisionSessionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGroupDecisionSession_Imports()
  {
    return (EReference)groupDecisionSessionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGroupDecisionSession_DecisionSupport()
  {
    return (EReference)groupDecisionSessionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLibDesRun()
  {
    return libDesRunEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLibDesRun_Library()
  {
    return (EReference)libDesRunEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLibDesRun_Designtime()
  {
    return (EReference)libDesRunEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLibDesRun_Runtime()
  {
    return (EReference)libDesRunEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImport()
  {
    return importEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImport_ImportURI()
  {
    return (EAttribute)importEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLibrary()
  {
    return libraryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLibrary_Name()
  {
    return (EAttribute)libraryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLibrary_Decisionrules()
  {
    return (EReference)libraryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLibrary_Algorithms()
  {
    return (EReference)libraryEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLibrary_Strategies()
  {
    return (EReference)libraryEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStrategy()
  {
    return strategyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStrategy_Name()
  {
    return (EAttribute)strategyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStrategy_PreferenceIndication()
  {
    return (EAttribute)strategyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStrategy_Rules()
  {
    return (EReference)strategyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStrategyPredefined()
  {
    return strategyPredefinedEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStrategyPredefined_Name()
  {
    return (EAttribute)strategyPredefinedEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStrategyPredefined_Rules()
  {
    return (EReference)strategyPredefinedEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRule()
  {
    return ruleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPredefinedRule()
  {
    return predefinedRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStrategyDecisionRule()
  {
    return strategyDecisionRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStrategyDecisionRule_Decisionrule()
  {
    return (EReference)strategyDecisionRuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStrategyDecisionRule_Teamprofiles()
  {
    return (EReference)strategyDecisionRuleEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPredefinedDecisionRule()
  {
    return predefinedDecisionRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPredefinedDecisionRule_Decisionrule()
  {
    return (EReference)predefinedDecisionRuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStrategyAlgorithm()
  {
    return strategyAlgorithmEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStrategyAlgorithm_Algorithm()
  {
    return (EReference)strategyAlgorithmEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDecisionRule()
  {
    return decisionRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDecisionRule_Name()
  {
    return (EAttribute)decisionRuleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDecisionRule_PrefIndAccepted()
  {
    return (EAttribute)decisionRuleEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDecisionRule_Description()
  {
    return (EAttribute)decisionRuleEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAlgorithm()
  {
    return algorithmEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlgorithm_Name()
  {
    return (EAttribute)algorithmEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlgorithm_PrefIndAccepted()
  {
    return (EAttribute)algorithmEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlgorithm_ConsidersTP()
  {
    return (EAttribute)algorithmEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlgorithm_Description()
  {
    return (EAttribute)algorithmEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDesignTime()
  {
    return designTimeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDesignTime_Decisionsupport()
  {
    return (EReference)designTimeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDecisionSupport()
  {
    return decisionSupportEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDecisionSupport_Name()
  {
    return (EAttribute)decisionSupportEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDecisionSupport_Makedecisionfor()
  {
    return (EReference)decisionSupportEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDecisionSupport_Strat()
  {
    return (EReference)decisionSupportEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStrat()
  {
    return stratEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStrat_Strat()
  {
    return (EReference)stratEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStrat_SolutionSelectedChosen()
  {
    return (EAttribute)stratEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStrat_Teamprofiles()
  {
    return (EReference)stratEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRunTime()
  {
    return runTimeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRunTime_Decisionsupport()
  {
    return (EReference)runTimeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRunTime_Category()
  {
    return (EReference)runTimeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRunTime_Saddresult()
  {
    return (EReference)runTimeEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSADDResult()
  {
    return saddResultEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSADDResult_Sadd()
  {
    return (EReference)saddResultEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSADDResult_Altpreferences()
  {
    return (EReference)saddResultEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAlternativePreference()
  {
    return alternativePreferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternativePreference_Alternative()
  {
    return (EReference)alternativePreferenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlternativePreference_Preferences()
  {
    return (EReference)alternativePreferenceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPreference()
  {
    return preferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPreference_Actor()
  {
    return (EReference)preferenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPreference_Value()
  {
    return (EAttribute)preferenceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPreference_Rationale()
  {
    return (EAttribute)preferenceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getPreferenceIndicationKind()
  {
    return preferenceIndicationKindEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getBOOLEAN()
  {
    return booleanEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DecisionmakingFactory getDecisionmakingFactory()
  {
    return (DecisionmakingFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    groupDecisionSessionEClass = createEClass(GROUP_DECISION_SESSION);
    createEReference(groupDecisionSessionEClass, GROUP_DECISION_SESSION__IMPORTS);
    createEReference(groupDecisionSessionEClass, GROUP_DECISION_SESSION__DECISION_SUPPORT);

    libDesRunEClass = createEClass(LIB_DES_RUN);
    createEReference(libDesRunEClass, LIB_DES_RUN__LIBRARY);
    createEReference(libDesRunEClass, LIB_DES_RUN__DESIGNTIME);
    createEReference(libDesRunEClass, LIB_DES_RUN__RUNTIME);

    importEClass = createEClass(IMPORT);
    createEAttribute(importEClass, IMPORT__IMPORT_URI);

    libraryEClass = createEClass(LIBRARY);
    createEAttribute(libraryEClass, LIBRARY__NAME);
    createEReference(libraryEClass, LIBRARY__DECISIONRULES);
    createEReference(libraryEClass, LIBRARY__ALGORITHMS);
    createEReference(libraryEClass, LIBRARY__STRATEGIES);

    strategyEClass = createEClass(STRATEGY);
    createEAttribute(strategyEClass, STRATEGY__NAME);
    createEAttribute(strategyEClass, STRATEGY__PREFERENCE_INDICATION);
    createEReference(strategyEClass, STRATEGY__RULES);

    strategyPredefinedEClass = createEClass(STRATEGY_PREDEFINED);
    createEAttribute(strategyPredefinedEClass, STRATEGY_PREDEFINED__NAME);
    createEReference(strategyPredefinedEClass, STRATEGY_PREDEFINED__RULES);

    ruleEClass = createEClass(RULE);

    predefinedRuleEClass = createEClass(PREDEFINED_RULE);

    strategyDecisionRuleEClass = createEClass(STRATEGY_DECISION_RULE);
    createEReference(strategyDecisionRuleEClass, STRATEGY_DECISION_RULE__DECISIONRULE);
    createEReference(strategyDecisionRuleEClass, STRATEGY_DECISION_RULE__TEAMPROFILES);

    predefinedDecisionRuleEClass = createEClass(PREDEFINED_DECISION_RULE);
    createEReference(predefinedDecisionRuleEClass, PREDEFINED_DECISION_RULE__DECISIONRULE);

    strategyAlgorithmEClass = createEClass(STRATEGY_ALGORITHM);
    createEReference(strategyAlgorithmEClass, STRATEGY_ALGORITHM__ALGORITHM);

    decisionRuleEClass = createEClass(DECISION_RULE);
    createEAttribute(decisionRuleEClass, DECISION_RULE__NAME);
    createEAttribute(decisionRuleEClass, DECISION_RULE__PREF_IND_ACCEPTED);
    createEAttribute(decisionRuleEClass, DECISION_RULE__DESCRIPTION);

    algorithmEClass = createEClass(ALGORITHM);
    createEAttribute(algorithmEClass, ALGORITHM__NAME);
    createEAttribute(algorithmEClass, ALGORITHM__PREF_IND_ACCEPTED);
    createEAttribute(algorithmEClass, ALGORITHM__CONSIDERS_TP);
    createEAttribute(algorithmEClass, ALGORITHM__DESCRIPTION);

    designTimeEClass = createEClass(DESIGN_TIME);
    createEReference(designTimeEClass, DESIGN_TIME__DECISIONSUPPORT);

    decisionSupportEClass = createEClass(DECISION_SUPPORT);
    createEAttribute(decisionSupportEClass, DECISION_SUPPORT__NAME);
    createEReference(decisionSupportEClass, DECISION_SUPPORT__MAKEDECISIONFOR);
    createEReference(decisionSupportEClass, DECISION_SUPPORT__STRAT);

    stratEClass = createEClass(STRAT);
    createEReference(stratEClass, STRAT__STRAT);
    createEAttribute(stratEClass, STRAT__SOLUTION_SELECTED_CHOSEN);
    createEReference(stratEClass, STRAT__TEAMPROFILES);

    runTimeEClass = createEClass(RUN_TIME);
    createEReference(runTimeEClass, RUN_TIME__DECISIONSUPPORT);
    createEReference(runTimeEClass, RUN_TIME__CATEGORY);
    createEReference(runTimeEClass, RUN_TIME__SADDRESULT);

    saddResultEClass = createEClass(SADD_RESULT);
    createEReference(saddResultEClass, SADD_RESULT__SADD);
    createEReference(saddResultEClass, SADD_RESULT__ALTPREFERENCES);

    alternativePreferenceEClass = createEClass(ALTERNATIVE_PREFERENCE);
    createEReference(alternativePreferenceEClass, ALTERNATIVE_PREFERENCE__ALTERNATIVE);
    createEReference(alternativePreferenceEClass, ALTERNATIVE_PREFERENCE__PREFERENCES);

    preferenceEClass = createEClass(PREFERENCE);
    createEReference(preferenceEClass, PREFERENCE__ACTOR);
    createEAttribute(preferenceEClass, PREFERENCE__VALUE);
    createEAttribute(preferenceEClass, PREFERENCE__RATIONALE);

    // Create enums
    preferenceIndicationKindEEnum = createEEnum(PREFERENCE_INDICATION_KIND);
    booleanEEnum = createEEnum(BOOLEAN);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    TeamprofilePackage theTeamprofilePackage = (TeamprofilePackage)EPackage.Registry.INSTANCE.getEPackage(TeamprofilePackage.eNS_URI);
    SaddPackage theSaddPackage = (SaddPackage)EPackage.Registry.INSTANCE.getEPackage(SaddPackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    strategyEClass.getESuperTypes().add(this.getStrat());
    strategyDecisionRuleEClass.getESuperTypes().add(this.getRule());
    predefinedDecisionRuleEClass.getESuperTypes().add(this.getPredefinedRule());
    strategyAlgorithmEClass.getESuperTypes().add(this.getRule());
    strategyAlgorithmEClass.getESuperTypes().add(this.getPredefinedRule());

    // Initialize classes and features; add operations and parameters
    initEClass(groupDecisionSessionEClass, GroupDecisionSession.class, "GroupDecisionSession", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGroupDecisionSession_Imports(), this.getImport(), null, "imports", null, 0, -1, GroupDecisionSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGroupDecisionSession_DecisionSupport(), this.getLibDesRun(), null, "decisionSupport", null, 0, 1, GroupDecisionSession.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(libDesRunEClass, LibDesRun.class, "LibDesRun", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLibDesRun_Library(), this.getLibrary(), null, "library", null, 0, 1, LibDesRun.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLibDesRun_Designtime(), this.getDesignTime(), null, "designtime", null, 0, 1, LibDesRun.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLibDesRun_Runtime(), this.getRunTime(), null, "runtime", null, 0, 1, LibDesRun.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(importEClass, Import.class, "Import", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getImport_ImportURI(), ecorePackage.getEString(), "importURI", null, 0, 1, Import.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(libraryEClass, Library.class, "Library", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLibrary_Name(), ecorePackage.getEString(), "name", null, 0, 1, Library.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLibrary_Decisionrules(), this.getDecisionRule(), null, "decisionrules", null, 0, -1, Library.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLibrary_Algorithms(), this.getAlgorithm(), null, "algorithms", null, 0, -1, Library.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLibrary_Strategies(), this.getStrategyPredefined(), null, "strategies", null, 0, -1, Library.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(strategyEClass, Strategy.class, "Strategy", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStrategy_Name(), ecorePackage.getEString(), "name", null, 0, 1, Strategy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStrategy_PreferenceIndication(), this.getPreferenceIndicationKind(), "preferenceIndication", null, 0, 1, Strategy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStrategy_Rules(), this.getRule(), null, "rules", null, 0, -1, Strategy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(strategyPredefinedEClass, StrategyPredefined.class, "StrategyPredefined", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStrategyPredefined_Name(), ecorePackage.getEString(), "name", null, 0, 1, StrategyPredefined.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStrategyPredefined_Rules(), this.getPredefinedRule(), null, "rules", null, 0, -1, StrategyPredefined.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ruleEClass, Rule.class, "Rule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(predefinedRuleEClass, PredefinedRule.class, "PredefinedRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(strategyDecisionRuleEClass, StrategyDecisionRule.class, "StrategyDecisionRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStrategyDecisionRule_Decisionrule(), this.getDecisionRule(), null, "decisionrule", null, 0, 1, StrategyDecisionRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStrategyDecisionRule_Teamprofiles(), theTeamprofilePackage.getProfile(), null, "teamprofiles", null, 0, -1, StrategyDecisionRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(predefinedDecisionRuleEClass, PredefinedDecisionRule.class, "PredefinedDecisionRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPredefinedDecisionRule_Decisionrule(), this.getDecisionRule(), null, "decisionrule", null, 0, 1, PredefinedDecisionRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(strategyAlgorithmEClass, StrategyAlgorithm.class, "StrategyAlgorithm", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStrategyAlgorithm_Algorithm(), this.getAlgorithm(), null, "algorithm", null, 0, 1, StrategyAlgorithm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(decisionRuleEClass, DecisionRule.class, "DecisionRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDecisionRule_Name(), ecorePackage.getEString(), "name", null, 0, 1, DecisionRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDecisionRule_PrefIndAccepted(), this.getPreferenceIndicationKind(), "prefIndAccepted", null, 0, -1, DecisionRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDecisionRule_Description(), ecorePackage.getEString(), "description", null, 0, 1, DecisionRule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(algorithmEClass, Algorithm.class, "Algorithm", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAlgorithm_Name(), ecorePackage.getEString(), "name", null, 0, 1, Algorithm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlgorithm_PrefIndAccepted(), this.getPreferenceIndicationKind(), "prefIndAccepted", null, 0, -1, Algorithm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlgorithm_ConsidersTP(), this.getBOOLEAN(), "considersTP", null, 0, 1, Algorithm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlgorithm_Description(), ecorePackage.getEString(), "description", null, 0, 1, Algorithm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(designTimeEClass, DesignTime.class, "DesignTime", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDesignTime_Decisionsupport(), this.getDecisionSupport(), null, "decisionsupport", null, 0, 1, DesignTime.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(decisionSupportEClass, DecisionSupport.class, "DecisionSupport", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDecisionSupport_Name(), ecorePackage.getEString(), "name", null, 0, 1, DecisionSupport.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDecisionSupport_Makedecisionfor(), theSaddPackage.getCategory(), null, "makedecisionfor", null, 0, -1, DecisionSupport.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDecisionSupport_Strat(), this.getStrat(), null, "strat", null, 0, -1, DecisionSupport.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stratEClass, Strat.class, "Strat", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStrat_Strat(), this.getStrategyPredefined(), null, "strat", null, 0, 1, Strat.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStrat_SolutionSelectedChosen(), this.getPreferenceIndicationKind(), "solutionSelectedChosen", null, 0, 1, Strat.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStrat_Teamprofiles(), theTeamprofilePackage.getProfile(), null, "teamprofiles", null, 0, -1, Strat.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(runTimeEClass, RunTime.class, "RunTime", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRunTime_Decisionsupport(), this.getDecisionSupport(), null, "decisionsupport", null, 0, 1, RunTime.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRunTime_Category(), theSaddPackage.getCategory(), null, "category", null, 0, 1, RunTime.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRunTime_Saddresult(), this.getSADDResult(), null, "saddresult", null, 0, -1, RunTime.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(saddResultEClass, SADDResult.class, "SADDResult", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSADDResult_Sadd(), theSaddPackage.getSecurityADD(), null, "sadd", null, 0, 1, SADDResult.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSADDResult_Altpreferences(), this.getAlternativePreference(), null, "altpreferences", null, 0, -1, SADDResult.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(alternativePreferenceEClass, AlternativePreference.class, "AlternativePreference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAlternativePreference_Alternative(), theSaddPackage.getAlternative(), null, "alternative", null, 0, 1, AlternativePreference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlternativePreference_Preferences(), this.getPreference(), null, "preferences", null, 0, -1, AlternativePreference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(preferenceEClass, Preference.class, "Preference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPreference_Actor(), theTeamprofilePackage.getActor(), null, "actor", null, 0, 1, Preference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPreference_Value(), ecorePackage.getEInt(), "value", null, 0, 1, Preference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPreference_Rationale(), ecorePackage.getEString(), "rationale", null, 0, 1, Preference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(preferenceIndicationKindEEnum, PreferenceIndicationKind.class, "PreferenceIndicationKind");
    addEEnumLiteral(preferenceIndicationKindEEnum, PreferenceIndicationKind.RANKING);
    addEEnumLiteral(preferenceIndicationKindEEnum, PreferenceIndicationKind.RATING);
    addEEnumLiteral(preferenceIndicationKindEEnum, PreferenceIndicationKind.YESNO);

    initEEnum(booleanEEnum, xtext.decisionmaking.BOOLEAN.class, "BOOLEAN");
    addEEnumLiteral(booleanEEnum, xtext.decisionmaking.BOOLEAN.NO);
    addEEnumLiteral(booleanEEnum, xtext.decisionmaking.BOOLEAN.YES);

    // Create resource
    createResource(eNS_URI);
  }

} //DecisionmakingPackageImpl
