/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtext.decisionmaking.Algorithm;
import xtext.decisionmaking.DecisionmakingPackage;
import xtext.decisionmaking.StrategyAlgorithm;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Strategy Algorithm</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.impl.StrategyAlgorithmImpl#getAlgorithm <em>Algorithm</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StrategyAlgorithmImpl extends RuleImpl implements StrategyAlgorithm
{
  /**
   * The cached value of the '{@link #getAlgorithm() <em>Algorithm</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlgorithm()
   * @generated
   * @ordered
   */
  protected Algorithm algorithm;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StrategyAlgorithmImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DecisionmakingPackage.Literals.STRATEGY_ALGORITHM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Algorithm getAlgorithm()
  {
    if (algorithm != null && algorithm.eIsProxy())
    {
      InternalEObject oldAlgorithm = (InternalEObject)algorithm;
      algorithm = (Algorithm)eResolveProxy(oldAlgorithm);
      if (algorithm != oldAlgorithm)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DecisionmakingPackage.STRATEGY_ALGORITHM__ALGORITHM, oldAlgorithm, algorithm));
      }
    }
    return algorithm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Algorithm basicGetAlgorithm()
  {
    return algorithm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlgorithm(Algorithm newAlgorithm)
  {
    Algorithm oldAlgorithm = algorithm;
    algorithm = newAlgorithm;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DecisionmakingPackage.STRATEGY_ALGORITHM__ALGORITHM, oldAlgorithm, algorithm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRATEGY_ALGORITHM__ALGORITHM:
        if (resolve) return getAlgorithm();
        return basicGetAlgorithm();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRATEGY_ALGORITHM__ALGORITHM:
        setAlgorithm((Algorithm)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRATEGY_ALGORITHM__ALGORITHM:
        setAlgorithm((Algorithm)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRATEGY_ALGORITHM__ALGORITHM:
        return algorithm != null;
    }
    return super.eIsSet(featureID);
  }

} //StrategyAlgorithmImpl
