/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import xtext.decisionmaking.DecisionRule;
import xtext.decisionmaking.DecisionmakingPackage;
import xtext.decisionmaking.StrategyDecisionRule;

import xtext.teamprofile.Profile;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Strategy Decision Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.impl.StrategyDecisionRuleImpl#getDecisionrule <em>Decisionrule</em>}</li>
 *   <li>{@link xtext.decisionmaking.impl.StrategyDecisionRuleImpl#getTeamprofiles <em>Teamprofiles</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StrategyDecisionRuleImpl extends RuleImpl implements StrategyDecisionRule
{
  /**
   * The cached value of the '{@link #getDecisionrule() <em>Decisionrule</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecisionrule()
   * @generated
   * @ordered
   */
  protected DecisionRule decisionrule;

  /**
   * The cached value of the '{@link #getTeamprofiles() <em>Teamprofiles</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeamprofiles()
   * @generated
   * @ordered
   */
  protected EList<Profile> teamprofiles;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StrategyDecisionRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DecisionmakingPackage.Literals.STRATEGY_DECISION_RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DecisionRule getDecisionrule()
  {
    if (decisionrule != null && decisionrule.eIsProxy())
    {
      InternalEObject oldDecisionrule = (InternalEObject)decisionrule;
      decisionrule = (DecisionRule)eResolveProxy(oldDecisionrule);
      if (decisionrule != oldDecisionrule)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DecisionmakingPackage.STRATEGY_DECISION_RULE__DECISIONRULE, oldDecisionrule, decisionrule));
      }
    }
    return decisionrule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DecisionRule basicGetDecisionrule()
  {
    return decisionrule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDecisionrule(DecisionRule newDecisionrule)
  {
    DecisionRule oldDecisionrule = decisionrule;
    decisionrule = newDecisionrule;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DecisionmakingPackage.STRATEGY_DECISION_RULE__DECISIONRULE, oldDecisionrule, decisionrule));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Profile> getTeamprofiles()
  {
    if (teamprofiles == null)
    {
      teamprofiles = new EObjectResolvingEList<Profile>(Profile.class, this, DecisionmakingPackage.STRATEGY_DECISION_RULE__TEAMPROFILES);
    }
    return teamprofiles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRATEGY_DECISION_RULE__DECISIONRULE:
        if (resolve) return getDecisionrule();
        return basicGetDecisionrule();
      case DecisionmakingPackage.STRATEGY_DECISION_RULE__TEAMPROFILES:
        return getTeamprofiles();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRATEGY_DECISION_RULE__DECISIONRULE:
        setDecisionrule((DecisionRule)newValue);
        return;
      case DecisionmakingPackage.STRATEGY_DECISION_RULE__TEAMPROFILES:
        getTeamprofiles().clear();
        getTeamprofiles().addAll((Collection<? extends Profile>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRATEGY_DECISION_RULE__DECISIONRULE:
        setDecisionrule((DecisionRule)null);
        return;
      case DecisionmakingPackage.STRATEGY_DECISION_RULE__TEAMPROFILES:
        getTeamprofiles().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRATEGY_DECISION_RULE__DECISIONRULE:
        return decisionrule != null;
      case DecisionmakingPackage.STRATEGY_DECISION_RULE__TEAMPROFILES:
        return teamprofiles != null && !teamprofiles.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //StrategyDecisionRuleImpl
