/**
 * generated by Xtext 2.35.0
 */
package xtext.decisionmaking.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import xtext.decisionmaking.DecisionmakingPackage;
import xtext.decisionmaking.SolutionSelectionKind;
import xtext.decisionmaking.Strat;
import xtext.decisionmaking.StrategyPredefined;

import xtext.teamprofile.Profile;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Strat</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.decisionmaking.impl.StratImpl#getStrat <em>Strat</em>}</li>
 *   <li>{@link xtext.decisionmaking.impl.StratImpl#getSolutionSelectedChosen <em>Solution Selected Chosen</em>}</li>
 *   <li>{@link xtext.decisionmaking.impl.StratImpl#getTeamprofiles <em>Teamprofiles</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StratImpl extends MinimalEObjectImpl.Container implements Strat
{
  /**
   * The cached value of the '{@link #getStrat() <em>Strat</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStrat()
   * @generated
   * @ordered
   */
  protected StrategyPredefined strat;

  /**
   * The default value of the '{@link #getSolutionSelectedChosen() <em>Solution Selected Chosen</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSolutionSelectedChosen()
   * @generated
   * @ordered
   */
  protected static final SolutionSelectionKind SOLUTION_SELECTED_CHOSEN_EDEFAULT = SolutionSelectionKind.RANKING;

  /**
   * The cached value of the '{@link #getSolutionSelectedChosen() <em>Solution Selected Chosen</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSolutionSelectedChosen()
   * @generated
   * @ordered
   */
  protected SolutionSelectionKind solutionSelectedChosen = SOLUTION_SELECTED_CHOSEN_EDEFAULT;

  /**
   * The cached value of the '{@link #getTeamprofiles() <em>Teamprofiles</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeamprofiles()
   * @generated
   * @ordered
   */
  protected EList<Profile> teamprofiles;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StratImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DecisionmakingPackage.Literals.STRAT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StrategyPredefined getStrat()
  {
    if (strat != null && strat.eIsProxy())
    {
      InternalEObject oldStrat = (InternalEObject)strat;
      strat = (StrategyPredefined)eResolveProxy(oldStrat);
      if (strat != oldStrat)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DecisionmakingPackage.STRAT__STRAT, oldStrat, strat));
      }
    }
    return strat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StrategyPredefined basicGetStrat()
  {
    return strat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStrat(StrategyPredefined newStrat)
  {
    StrategyPredefined oldStrat = strat;
    strat = newStrat;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DecisionmakingPackage.STRAT__STRAT, oldStrat, strat));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SolutionSelectionKind getSolutionSelectedChosen()
  {
    return solutionSelectedChosen;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSolutionSelectedChosen(SolutionSelectionKind newSolutionSelectedChosen)
  {
    SolutionSelectionKind oldSolutionSelectedChosen = solutionSelectedChosen;
    solutionSelectedChosen = newSolutionSelectedChosen == null ? SOLUTION_SELECTED_CHOSEN_EDEFAULT : newSolutionSelectedChosen;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DecisionmakingPackage.STRAT__SOLUTION_SELECTED_CHOSEN, oldSolutionSelectedChosen, solutionSelectedChosen));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Profile> getTeamprofiles()
  {
    if (teamprofiles == null)
    {
      teamprofiles = new EObjectResolvingEList<Profile>(Profile.class, this, DecisionmakingPackage.STRAT__TEAMPROFILES);
    }
    return teamprofiles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRAT__STRAT:
        if (resolve) return getStrat();
        return basicGetStrat();
      case DecisionmakingPackage.STRAT__SOLUTION_SELECTED_CHOSEN:
        return getSolutionSelectedChosen();
      case DecisionmakingPackage.STRAT__TEAMPROFILES:
        return getTeamprofiles();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRAT__STRAT:
        setStrat((StrategyPredefined)newValue);
        return;
      case DecisionmakingPackage.STRAT__SOLUTION_SELECTED_CHOSEN:
        setSolutionSelectedChosen((SolutionSelectionKind)newValue);
        return;
      case DecisionmakingPackage.STRAT__TEAMPROFILES:
        getTeamprofiles().clear();
        getTeamprofiles().addAll((Collection<? extends Profile>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRAT__STRAT:
        setStrat((StrategyPredefined)null);
        return;
      case DecisionmakingPackage.STRAT__SOLUTION_SELECTED_CHOSEN:
        setSolutionSelectedChosen(SOLUTION_SELECTED_CHOSEN_EDEFAULT);
        return;
      case DecisionmakingPackage.STRAT__TEAMPROFILES:
        getTeamprofiles().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DecisionmakingPackage.STRAT__STRAT:
        return strat != null;
      case DecisionmakingPackage.STRAT__SOLUTION_SELECTED_CHOSEN:
        return solutionSelectedChosen != SOLUTION_SELECTED_CHOSEN_EDEFAULT;
      case DecisionmakingPackage.STRAT__TEAMPROFILES:
        return teamprofiles != null && !teamprofiles.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (solutionSelectedChosen: ");
    result.append(solutionSelectedChosen);
    result.append(')');
    return result.toString();
  }

} //StratImpl
