/*
 * generated by Xtext 2.35.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TeamprofileStandaloneSetup extends TeamprofileStandaloneSetupGenerated {

	public static void doSetup() {
		new TeamprofileStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
