/*
 * generated by Xtext 2.35.0
 */
package xtext.semcomdt.swhumanfactor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HumanfactorUiModule extends AbstractHumanfactorUiModule {

	public HumanfactorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
