grammar xtext.semcomdt.swhumanfactor.Humanfactor with org.eclipse.xtext.common.Terminals

generate humanfactor "http://www.semcomdt.xtext/swhumanfactor/Humanfactor"


HFModel:
	imports+=Import*
	libraries+=HFLibraryKind*
	designtime=DesignTime?
;
Import:
	'import' importURI=STRING
;
HFLibraryKind :
	HFCategoryLibrary | HFPropertyLibrary | HFMeasurementLibrary
;
HFMeasurementLibrary:
	{HFMeasurementLibrary} 'HFMeasurementLibrary' 
	'{' 
		definesHFMeasurementScale+=HFMeasurementScale*
	'}'
;
HFCategoryLibrary:
	{HFCategoryLibrary} 'HFCategoryLibrary'
	'{' definesHFCategory+=HFCategory* '}'
;
HFPropertyLibrary:
	{HFPropertyLibrary} 'HFPropertyLibrary' 
	'{' definesHFProperty+=HFProperty* '}'
;

HFCatProp:
	HFCategory | HFProperty
;
HFCategory:
	name=ID
	('{' composedOf+=HFCategory* '}')*
;

HFProperty:
	name=ID "{"
	'isIn' isInCategory=[HFCategory|QualifiedName] & 
	'isMeasuredWith' isMeasuredWith=[HFMeasurementScale|QualifiedName] & //Name of the scale provided
	('isvaluedWith' isValuedWith=HFMeasurementValueType)? & //We verify if the value given here is the same as the valueset provided
	"}"
;

HFMeasurementScale:
	name=ID ':' type=HFScaleType '['
	(acceptedValues+=HFMeasurementValueType (',' acceptedValues+=HFMeasurementValueType)*)
	 ']'
;
HFMeasurementValueType :
	STRING | INT;
	
enum HFScaleType:
	nominal='Nominal' |
	ordinal='Ordinal' |
	interval='Interval' |
	ratioinfinitecontinuous='RatioInfiniteContinuous' |
	ratioinfinitediscrete='RatioInfiniteDiscrete' |
	ratiofinitediscrete='RatioFiniteDiscrete'
	
;
QualifiedName:
	ID ('.' ID)*
;

DesignTime:
	"DesignTime" name=ID "{"
		("-" hfproperties+=[HFProperty|QualifiedName])*
		"}"
;
