/**
 * generated by Xtext 2.35.0
 */
package xtext.sadd.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import xtext.sadd.Category;
import xtext.sadd.Project;
import xtext.sadd.SaddPackage;
import xtext.sadd.SecurityADD;

import xtext.teamprofile.Profile;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.sadd.impl.ProjectImpl#getTeamprofiles <em>Teamprofiles</em>}</li>
 *   <li>{@link xtext.sadd.impl.ProjectImpl#getSecadd <em>Secadd</em>}</li>
 *   <li>{@link xtext.sadd.impl.ProjectImpl#getCategory <em>Category</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProjectImpl extends ProjCatSADDImpl implements Project
{
  /**
   * The cached value of the '{@link #getTeamprofiles() <em>Teamprofiles</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTeamprofiles()
   * @generated
   * @ordered
   */
  protected EList<Profile> teamprofiles;

  /**
   * The cached value of the '{@link #getSecadd() <em>Secadd</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecadd()
   * @generated
   * @ordered
   */
  protected EList<SecurityADD> secadd;

  /**
   * The cached value of the '{@link #getCategory() <em>Category</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategory()
   * @generated
   * @ordered
   */
  protected EList<Category> category;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SaddPackage.Literals.PROJECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Profile> getTeamprofiles()
  {
    if (teamprofiles == null)
    {
      teamprofiles = new EObjectResolvingEList<Profile>(Profile.class, this, SaddPackage.PROJECT__TEAMPROFILES);
    }
    return teamprofiles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SecurityADD> getSecadd()
  {
    if (secadd == null)
    {
      secadd = new EObjectContainmentEList<SecurityADD>(SecurityADD.class, this, SaddPackage.PROJECT__SECADD);
    }
    return secadd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Category> getCategory()
  {
    if (category == null)
    {
      category = new EObjectContainmentEList<Category>(Category.class, this, SaddPackage.PROJECT__CATEGORY);
    }
    return category;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SaddPackage.PROJECT__SECADD:
        return ((InternalEList<?>)getSecadd()).basicRemove(otherEnd, msgs);
      case SaddPackage.PROJECT__CATEGORY:
        return ((InternalEList<?>)getCategory()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SaddPackage.PROJECT__TEAMPROFILES:
        return getTeamprofiles();
      case SaddPackage.PROJECT__SECADD:
        return getSecadd();
      case SaddPackage.PROJECT__CATEGORY:
        return getCategory();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SaddPackage.PROJECT__TEAMPROFILES:
        getTeamprofiles().clear();
        getTeamprofiles().addAll((Collection<? extends Profile>)newValue);
        return;
      case SaddPackage.PROJECT__SECADD:
        getSecadd().clear();
        getSecadd().addAll((Collection<? extends SecurityADD>)newValue);
        return;
      case SaddPackage.PROJECT__CATEGORY:
        getCategory().clear();
        getCategory().addAll((Collection<? extends Category>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SaddPackage.PROJECT__TEAMPROFILES:
        getTeamprofiles().clear();
        return;
      case SaddPackage.PROJECT__SECADD:
        getSecadd().clear();
        return;
      case SaddPackage.PROJECT__CATEGORY:
        getCategory().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SaddPackage.PROJECT__TEAMPROFILES:
        return teamprofiles != null && !teamprofiles.isEmpty();
      case SaddPackage.PROJECT__SECADD:
        return secadd != null && !secadd.isEmpty();
      case SaddPackage.PROJECT__CATEGORY:
        return category != null && !category.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ProjectImpl
