/*
 * generated by Xtext 2.35.0
 */
package xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import xtext.services.TeamprofileGrammarAccess;
import xtext.teamprofile.Actor;
import xtext.teamprofile.Attribute;
import xtext.teamprofile.Import;
import xtext.teamprofile.Profile;
import xtext.teamprofile.Profiling;
import xtext.teamprofile.TeamprofilePackage;

@SuppressWarnings("all")
public class TeamprofileSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private TeamprofileGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == TeamprofilePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TeamprofilePackage.ACTOR:
				sequence_Actor(context, (Actor) semanticObject); 
				return; 
			case TeamprofilePackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case TeamprofilePackage.IMPORT:
				sequence_Import(context, (Import) semanticObject); 
				return; 
			case TeamprofilePackage.PROFILE:
				sequence_Profile(context, (Profile) semanticObject); 
				return; 
			case TeamprofilePackage.PROFILING:
				sequence_Profiling(context, (Profiling) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Actor returns Actor
	 *
	 * Constraint:
	 *     (name=ID attributes+=Attribute+)
	 * </pre>
	 */
	protected void sequence_Actor(ISerializationContext context, Actor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Attribute returns Attribute
	 *
	 * Constraint:
	 *     (hfproperty=STRING hfmeasurementvalue=ValueKind)
	 * </pre>
	 */
	protected void sequence_Attribute(ISerializationContext context, Attribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TeamprofilePackage.Literals.ATTRIBUTE__HFPROPERTY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TeamprofilePackage.Literals.ATTRIBUTE__HFPROPERTY));
			if (transientValues.isValueTransient(semanticObject, TeamprofilePackage.Literals.ATTRIBUTE__HFMEASUREMENTVALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TeamprofilePackage.Literals.ATTRIBUTE__HFMEASUREMENTVALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAttributeAccess().getHfpropertySTRINGTerminalRuleCall_0_0(), semanticObject.getHfproperty());
		feeder.accept(grammarAccess.getAttributeAccess().getHfmeasurementvalueValueKindParserRuleCall_2_0(), semanticObject.getHfmeasurementvalue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Import returns Import
	 *
	 * Constraint:
	 *     importURI=STRING
	 * </pre>
	 */
	protected void sequence_Import(ISerializationContext context, Import semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, TeamprofilePackage.Literals.IMPORT__IMPORT_URI) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, TeamprofilePackage.Literals.IMPORT__IMPORT_URI));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getImportAccess().getImportURISTRINGTerminalRuleCall_1_0(), semanticObject.getImportURI());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Profile returns Profile
	 *
	 * Constraint:
	 *     (name=ID actors+=[Actor|ID]* attributes+=Attribute+)
	 * </pre>
	 */
	protected void sequence_Profile(ISerializationContext context, Profile semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Profiling returns Profiling
	 *
	 * Constraint:
	 *     ((imports+=Import* actors+=Actor+ profiles+=Profile+) | (imports+=Import* profiles+=Profile+) | profiles+=Profile+)?
	 * </pre>
	 */
	protected void sequence_Profiling(ISerializationContext context, Profiling semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
