/*
 * generated by Xtext 2.35.0
 */
grammar InternalTeamprofile;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package xtext.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package xtext.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import xtext.services.TeamprofileGrammarAccess;

}
@parser::members {
	private TeamprofileGrammarAccess grammarAccess;

	public void setGrammarAccess(TeamprofileGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleProfiling
entryRuleProfiling
:
{ before(grammarAccess.getProfilingRule()); }
	 ruleProfiling
{ after(grammarAccess.getProfilingRule()); } 
	 EOF 
;

// Rule Profiling
ruleProfiling 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getProfilingAccess().getGroup()); }
		(rule__Profiling__Group__0)
		{ after(grammarAccess.getProfilingAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleImport
entryRuleImport
:
{ before(grammarAccess.getImportRule()); }
	 ruleImport
{ after(grammarAccess.getImportRule()); } 
	 EOF 
;

// Rule Import
ruleImport 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getImportAccess().getGroup()); }
		(rule__Import__Group__0)
		{ after(grammarAccess.getImportAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleActor
entryRuleActor
:
{ before(grammarAccess.getActorRule()); }
	 ruleActor
{ after(grammarAccess.getActorRule()); } 
	 EOF 
;

// Rule Actor
ruleActor 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getActorAccess().getGroup()); }
		(rule__Actor__Group__0)
		{ after(grammarAccess.getActorAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleProfile
entryRuleProfile
:
{ before(grammarAccess.getProfileRule()); }
	 ruleProfile
{ after(grammarAccess.getProfileRule()); } 
	 EOF 
;

// Rule Profile
ruleProfile 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getProfileAccess().getGroup()); }
		(rule__Profile__Group__0)
		{ after(grammarAccess.getProfileAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAttribute
entryRuleAttribute
:
{ before(grammarAccess.getAttributeRule()); }
	 ruleAttribute
{ after(grammarAccess.getAttributeRule()); } 
	 EOF 
;

// Rule Attribute
ruleAttribute 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAttributeAccess().getGroup()); }
		(rule__Attribute__Group__0)
		{ after(grammarAccess.getAttributeAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleValueKind
entryRuleValueKind
:
{ before(grammarAccess.getValueKindRule()); }
	 ruleValueKind
{ after(grammarAccess.getValueKindRule()); } 
	 EOF 
;

// Rule ValueKind
ruleValueKind 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getValueKindAccess().getAlternatives()); }
		(rule__ValueKind__Alternatives)
		{ after(grammarAccess.getValueKindAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ValueKind__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getValueKindAccess().getINTTerminalRuleCall_0()); }
		RULE_INT
		{ after(grammarAccess.getValueKindAccess().getINTTerminalRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getValueKindAccess().getSTRINGTerminalRuleCall_1()); }
		RULE_STRING
		{ after(grammarAccess.getValueKindAccess().getSTRINGTerminalRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profiling__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profiling__Group__0__Impl
	rule__Profiling__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Profiling__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfilingAccess().getImportsAssignment_0()); }
	(rule__Profiling__ImportsAssignment_0)*
	{ after(grammarAccess.getProfilingAccess().getImportsAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profiling__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profiling__Group__1__Impl
	rule__Profiling__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Profiling__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfilingAccess().getActorsAssignment_1()); }
	(rule__Profiling__ActorsAssignment_1)*
	{ after(grammarAccess.getProfilingAccess().getActorsAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profiling__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profiling__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Profiling__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfilingAccess().getProfilesAssignment_2()); }
	(rule__Profiling__ProfilesAssignment_2)*
	{ after(grammarAccess.getProfilingAccess().getProfilesAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Import__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Import__Group__0__Impl
	rule__Import__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Import__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getImportAccess().getImportKeyword_0()); }
	'import'
	{ after(grammarAccess.getImportAccess().getImportKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Import__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Import__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Import__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getImportAccess().getImportURIAssignment_1()); }
	(rule__Import__ImportURIAssignment_1)
	{ after(grammarAccess.getImportAccess().getImportURIAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Actor__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Actor__Group__0__Impl
	rule__Actor__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Actor__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getActorAccess().getActorKeyword_0()); }
	'Actor'
	{ after(grammarAccess.getActorAccess().getActorKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Actor__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Actor__Group__1__Impl
	rule__Actor__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Actor__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getActorAccess().getNameAssignment_1()); }
	(rule__Actor__NameAssignment_1)
	{ after(grammarAccess.getActorAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Actor__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Actor__Group__2__Impl
	rule__Actor__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Actor__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getActorAccess().getColonKeyword_2()); }
	':'
	{ after(grammarAccess.getActorAccess().getColonKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Actor__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Actor__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Actor__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getActorAccess().getAttributesAssignment_3()); }
		(rule__Actor__AttributesAssignment_3)
		{ after(grammarAccess.getActorAccess().getAttributesAssignment_3()); }
	)
	(
		{ before(grammarAccess.getActorAccess().getAttributesAssignment_3()); }
		(rule__Actor__AttributesAssignment_3)*
		{ after(grammarAccess.getActorAccess().getAttributesAssignment_3()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Profile__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profile__Group__0__Impl
	rule__Profile__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfileAccess().getNameAssignment_0()); }
	(rule__Profile__NameAssignment_0)
	{ after(grammarAccess.getProfileAccess().getNameAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profile__Group__1__Impl
	rule__Profile__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfileAccess().getGroup_1()); }
	(rule__Profile__Group_1__0)*
	{ after(grammarAccess.getProfileAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profile__Group__2__Impl
	rule__Profile__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfileAccess().getCharacterizedByKeyword_2()); }
	'characterizedBy'
	{ after(grammarAccess.getProfileAccess().getCharacterizedByKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profile__Group__3__Impl
	rule__Profile__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfileAccess().getLeftCurlyBracketKeyword_3()); }
	'{'
	{ after(grammarAccess.getProfileAccess().getLeftCurlyBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profile__Group__4__Impl
	rule__Profile__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	(
		{ before(grammarAccess.getProfileAccess().getAttributesAssignment_4()); }
		(rule__Profile__AttributesAssignment_4)
		{ after(grammarAccess.getProfileAccess().getAttributesAssignment_4()); }
	)
	(
		{ before(grammarAccess.getProfileAccess().getAttributesAssignment_4()); }
		(rule__Profile__AttributesAssignment_4)*
		{ after(grammarAccess.getProfileAccess().getAttributesAssignment_4()); }
	)
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profile__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfileAccess().getRightCurlyBracketKeyword_5()); }
	'}'
	{ after(grammarAccess.getProfileAccess().getRightCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Profile__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profile__Group_1__0__Impl
	rule__Profile__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfileAccess().getGathersKeyword_1_0()); }
	'gathers'
	{ after(grammarAccess.getProfileAccess().getGathersKeyword_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profile__Group_1__1__Impl
	rule__Profile__Group_1__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfileAccess().getLeftCurlyBracketKeyword_1_1()); }
	'{'
	{ after(grammarAccess.getProfileAccess().getLeftCurlyBracketKeyword_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profile__Group_1__2__Impl
	rule__Profile__Group_1__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group_1__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfileAccess().getActorsAssignment_1_2()); }
	(rule__Profile__ActorsAssignment_1_2)*
	{ after(grammarAccess.getProfileAccess().getActorsAssignment_1_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group_1__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Profile__Group_1__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__Group_1__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getProfileAccess().getRightCurlyBracketKeyword_1_3()); }
	'}'
	{ after(grammarAccess.getProfileAccess().getRightCurlyBracketKeyword_1_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Attribute__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Attribute__Group__0__Impl
	rule__Attribute__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Attribute__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAttributeAccess().getHfpropertyAssignment_0()); }
	(rule__Attribute__HfpropertyAssignment_0)
	{ after(grammarAccess.getAttributeAccess().getHfpropertyAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Attribute__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Attribute__Group__1__Impl
	rule__Attribute__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Attribute__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAttributeAccess().getEqualsSignKeyword_1()); }
	'='
	{ after(grammarAccess.getAttributeAccess().getEqualsSignKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Attribute__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Attribute__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Attribute__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAttributeAccess().getHfmeasurementvalueAssignment_2()); }
	(rule__Attribute__HfmeasurementvalueAssignment_2)
	{ after(grammarAccess.getAttributeAccess().getHfmeasurementvalueAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Profiling__ImportsAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProfilingAccess().getImportsImportParserRuleCall_0_0()); }
		ruleImport
		{ after(grammarAccess.getProfilingAccess().getImportsImportParserRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profiling__ActorsAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProfilingAccess().getActorsActorParserRuleCall_1_0()); }
		ruleActor
		{ after(grammarAccess.getProfilingAccess().getActorsActorParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profiling__ProfilesAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProfilingAccess().getProfilesProfileParserRuleCall_2_0()); }
		ruleProfile
		{ after(grammarAccess.getProfilingAccess().getProfilesProfileParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Import__ImportURIAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getImportAccess().getImportURISTRINGTerminalRuleCall_1_0()); }
		RULE_STRING
		{ after(grammarAccess.getImportAccess().getImportURISTRINGTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Actor__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getActorAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getActorAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Actor__AttributesAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getActorAccess().getAttributesAttributeParserRuleCall_3_0()); }
		ruleAttribute
		{ after(grammarAccess.getActorAccess().getAttributesAttributeParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__NameAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProfileAccess().getNameIDTerminalRuleCall_0_0()); }
		RULE_ID
		{ after(grammarAccess.getProfileAccess().getNameIDTerminalRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__ActorsAssignment_1_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProfileAccess().getActorsActorCrossReference_1_2_0()); }
		(
			{ before(grammarAccess.getProfileAccess().getActorsActorIDTerminalRuleCall_1_2_0_1()); }
			RULE_ID
			{ after(grammarAccess.getProfileAccess().getActorsActorIDTerminalRuleCall_1_2_0_1()); }
		)
		{ after(grammarAccess.getProfileAccess().getActorsActorCrossReference_1_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Profile__AttributesAssignment_4
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getProfileAccess().getAttributesAttributeParserRuleCall_4_0()); }
		ruleAttribute
		{ after(grammarAccess.getProfileAccess().getAttributesAttributeParserRuleCall_4_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Attribute__HfpropertyAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAttributeAccess().getHfpropertySTRINGTerminalRuleCall_0_0()); }
		RULE_STRING
		{ after(grammarAccess.getAttributeAccess().getHfpropertySTRINGTerminalRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Attribute__HfmeasurementvalueAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAttributeAccess().getHfmeasurementvalueValueKindParserRuleCall_2_0()); }
		ruleValueKind
		{ after(grammarAccess.getAttributeAccess().getHfmeasurementvalueValueKindParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
