/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swsecurity;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SecurityaddStandaloneSetup extends SecurityaddStandaloneSetupGenerated {

	public static void doSetup() {
		new SecurityaddStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
