grammar semcomdt.swsecurity.Securityadd with org.eclipse.xtext.common.Terminals

generate securityadd "http://www.swsecurity.semcomdt/Securityadd"

Model:
	imports+=Import*
	libdesign=ProjCatSADD
;

Import:
	'import' importURI=STRING
;

ProjCatSADD :
	Project | Category | SecurityADD
;


Category :
	"Category" name=ID "{" secadd+=[SecurityADD|QualifiedName]* "}"
;

Project :
	"Project" name=ID  "{" 
	secadd+=SecurityADD*
	category+=Category*"}"
;

	
SecurityADD:
	'SecurityADD' name=ID 
	alts=Alternatives
;
Alternatives:
	'alternatives' "{" alternatives+=Alternative+ "}" | "selectedAlternatives" "{" ("-" selectedalternatives+=[Alternative|QualifiedName])+ "}"
;
Alternative:
	"-" name=ID "("solutions+=STRING+")"
;

QualifiedName:
	ID ('.' ID)*;
	
	