/*
 * generated by Xtext 2.35.0
 */
package xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.parser.antlr.internal.InternalSaddParser;
import xtext.services.SaddGrammarAccess;

public class SaddParser extends AbstractAntlrParser {

	@Inject
	private SaddGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSaddParser createParser(XtextTokenStream stream) {
		return new InternalSaddParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SaddGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SaddGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
