/*
 * generated by Xtext 2.35.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SaddUiModule extends AbstractSaddUiModule {

	public SaddUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
