/*
 * generated by Xtext 2.35.0
 */
package semcomdt.swhumanfactor.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import semcomdt.swhumanfactor.TeamprofileRuntimeModule;
import semcomdt.swhumanfactor.TeamprofileStandaloneSetup;
import semcomdt.swhumanfactor.ide.TeamprofileIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class TeamprofileWebSetup extends TeamprofileStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TeamprofileRuntimeModule(), new TeamprofileIdeModule(), new TeamprofileWebModule()));
	}
	
}
