/*
 * generated by Xtext 2.35.0
 */
package xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.parser.antlr.internal.InternalDecisionmakingParser;
import xtext.services.DecisionmakingGrammarAccess;

public class DecisionmakingParser extends AbstractAntlrParser {

	@Inject
	private DecisionmakingGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDecisionmakingParser createParser(XtextTokenStream stream) {
		return new InternalDecisionmakingParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GroupDecisionSession";
	}

	public DecisionmakingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DecisionmakingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
