/*
 * generated by Xtext 2.35.0
 */
grammar InternalDecisionmaking;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package xtext.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package xtext.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import xtext.services.DecisionmakingGrammarAccess;

}

@parser::members {

 	private DecisionmakingGrammarAccess grammarAccess;

    public InternalDecisionmakingParser(TokenStream input, DecisionmakingGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "GroupDecisionSession";
   	}

   	@Override
   	protected DecisionmakingGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleGroupDecisionSession
entryRuleGroupDecisionSession returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getGroupDecisionSessionRule()); }
	iv_ruleGroupDecisionSession=ruleGroupDecisionSession
	{ $current=$iv_ruleGroupDecisionSession.current; }
	EOF;

// Rule GroupDecisionSession
ruleGroupDecisionSession returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getGroupDecisionSessionAccess().getImportsImportParserRuleCall_0_0());
				}
				lv_imports_0_0=ruleImport
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getGroupDecisionSessionRule());
					}
					add(
						$current,
						"imports",
						lv_imports_0_0,
						"xtext.Decisionmaking.Import");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getGroupDecisionSessionAccess().getDecisionSupportLibDesRunParserRuleCall_1_0());
				}
				lv_decisionSupport_1_0=ruleLibDesRun
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getGroupDecisionSessionRule());
					}
					set(
						$current,
						"decisionSupport",
						lv_decisionSupport_1_0,
						"xtext.Decisionmaking.LibDesRun");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleLibDesRun
entryRuleLibDesRun returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLibDesRunRule()); }
	iv_ruleLibDesRun=ruleLibDesRun
	{ $current=$iv_ruleLibDesRun.current; }
	EOF;

// Rule LibDesRun
ruleLibDesRun returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getLibDesRunAccess().getLibraryLibraryParserRuleCall_0_0());
				}
				lv_library_0_0=ruleLibrary
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLibDesRunRule());
					}
					set(
						$current,
						"library",
						lv_library_0_0,
						"xtext.Decisionmaking.Library");
					afterParserOrEnumRuleCall();
				}
			)
		)
		    |
		(
			(
				{
					newCompositeNode(grammarAccess.getLibDesRunAccess().getDesigntimeDesignTimeParserRuleCall_1_0());
				}
				lv_designtime_1_0=ruleDesignTime
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLibDesRunRule());
					}
					set(
						$current,
						"designtime",
						lv_designtime_1_0,
						"xtext.Decisionmaking.DesignTime");
					afterParserOrEnumRuleCall();
				}
			)
		)
		    |
		(
			(
				{
					newCompositeNode(grammarAccess.getLibDesRunAccess().getRuntimeRunTimeParserRuleCall_2_0());
				}
				lv_runtime_2_0=ruleRunTime
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLibDesRunRule());
					}
					set(
						$current,
						"runtime",
						lv_runtime_2_0,
						"xtext.Decisionmaking.RunTime");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleImport
entryRuleImport returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getImportRule()); }
	iv_ruleImport=ruleImport
	{ $current=$iv_ruleImport.current; }
	EOF;

// Rule Import
ruleImport returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='import'
		{
			newLeafNode(otherlv_0, grammarAccess.getImportAccess().getImportKeyword_0());
		}
		(
			(
				lv_importURI_1_0=RULE_STRING
				{
					newLeafNode(lv_importURI_1_0, grammarAccess.getImportAccess().getImportURISTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getImportRule());
					}
					setWithLastConsumed(
						$current,
						"importURI",
						lv_importURI_1_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
	)
;

// Entry rule entryRuleLibrary
entryRuleLibrary returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLibraryRule()); }
	iv_ruleLibrary=ruleLibrary
	{ $current=$iv_ruleLibrary.current; }
	EOF;

// Rule Library
ruleLibrary returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{ 
			  getUnorderedGroupHelper().enter(grammarAccess.getLibraryAccess().getUnorderedGroup());
			}
			(
				(
		(
			{getUnorderedGroupHelper().canSelect(grammarAccess.getLibraryAccess().getUnorderedGroup(), 0)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getLibraryAccess().getUnorderedGroup(), 0);
				}
							({true}?=>(otherlv_1='Library'
							{
								newLeafNode(otherlv_1, grammarAccess.getLibraryAccess().getLibraryKeyword_0_0());
							}
							(
								(
									lv_name_2_0=RULE_ID
									{
										newLeafNode(lv_name_2_0, grammarAccess.getLibraryAccess().getNameIDTerminalRuleCall_0_1_0());
									}
									{
										if ($current==null) {
											$current = createModelElement(grammarAccess.getLibraryRule());
										}
										setWithLastConsumed(
											$current,
											"name",
											lv_name_2_0,
											"org.eclipse.xtext.common.Terminals.ID");
									}
								)
							)
							(
								(
									{
										newCompositeNode(grammarAccess.getLibraryAccess().getDecisionrulesDecisionRuleParserRuleCall_0_2_0());
									}
									lv_decisionrules_3_0=ruleDecisionRule
									{
										if ($current==null) {
											$current = createModelElementForParent(grammarAccess.getLibraryRule());
										}
										add(
											$current,
											"decisionrules",
											lv_decisionrules_3_0,
											"xtext.Decisionmaking.DecisionRule");
										afterParserOrEnumRuleCall();
									}
								)
							)*
							))
				{ 
					getUnorderedGroupHelper().returnFromSelection(grammarAccess.getLibraryAccess().getUnorderedGroup());
				}
			)
		)|
		(
			{getUnorderedGroupHelper().canSelect(grammarAccess.getLibraryAccess().getUnorderedGroup(), 1)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getLibraryAccess().getUnorderedGroup(), 1);
				}
							({true}?=>((
								{
									newCompositeNode(grammarAccess.getLibraryAccess().getAlgorithmsAlgorithmParserRuleCall_1_0());
								}
								lv_algorithms_4_0=ruleAlgorithm
								{
									if ($current==null) {
										$current = createModelElementForParent(grammarAccess.getLibraryRule());
									}
									add(
										$current,
										"algorithms",
										lv_algorithms_4_0,
										"xtext.Decisionmaking.Algorithm");
									afterParserOrEnumRuleCall();
								}
							)
							))+
				{ 
					getUnorderedGroupHelper().returnFromSelection(grammarAccess.getLibraryAccess().getUnorderedGroup());
				}
			)
		)|
		(
			{getUnorderedGroupHelper().canSelect(grammarAccess.getLibraryAccess().getUnorderedGroup(), 2)}?=>(
				{
					getUnorderedGroupHelper().select(grammarAccess.getLibraryAccess().getUnorderedGroup(), 2);
				}
							({true}?=>((
								{
									newCompositeNode(grammarAccess.getLibraryAccess().getStrategiesStrategyPredefinedParserRuleCall_2_0());
								}
								lv_strategies_5_0=ruleStrategyPredefined
								{
									if ($current==null) {
										$current = createModelElementForParent(grammarAccess.getLibraryRule());
									}
									add(
										$current,
										"strategies",
										lv_strategies_5_0,
										"xtext.Decisionmaking.StrategyPredefined");
									afterParserOrEnumRuleCall();
								}
							)
							))+
				{ 
					getUnorderedGroupHelper().returnFromSelection(grammarAccess.getLibraryAccess().getUnorderedGroup());
				}
			)
		)
				)+
				{getUnorderedGroupHelper().canLeave(grammarAccess.getLibraryAccess().getUnorderedGroup())}?
			)
		)
			{ 
			  getUnorderedGroupHelper().leave(grammarAccess.getLibraryAccess().getUnorderedGroup());
			}
	)
;

// Entry rule entryRuleStrategy
entryRuleStrategy returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStrategyRule()); }
	iv_ruleStrategy=ruleStrategy
	{ $current=$iv_ruleStrategy.current; }
	EOF;

// Rule Strategy
ruleStrategy returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Strategy'
		{
			newLeafNode(otherlv_0, grammarAccess.getStrategyAccess().getStrategyKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getStrategyAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getStrategyRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='withPreferenceIndication'
		{
			newLeafNode(otherlv_2, grammarAccess.getStrategyAccess().getWithPreferenceIndicationKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getStrategyAccess().getPreferenceIndicationPreferenceIndicationKindEnumRuleCall_3_0());
				}
				lv_preferenceIndication_3_0=rulePreferenceIndicationKind
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getStrategyRule());
					}
					set(
						$current,
						"preferenceIndication",
						lv_preferenceIndication_3_0,
						"xtext.Decisionmaking.PreferenceIndicationKind");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='{'
		{
			newLeafNode(otherlv_4, grammarAccess.getStrategyAccess().getLeftCurlyBracketKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getStrategyAccess().getRulesRuleParserRuleCall_5_0());
				}
				lv_rules_5_0=ruleRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getStrategyRule());
					}
					add(
						$current,
						"rules",
						lv_rules_5_0,
						"xtext.Decisionmaking.Rule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			otherlv_6='then'
			{
				newLeafNode(otherlv_6, grammarAccess.getStrategyAccess().getThenKeyword_6_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getStrategyAccess().getRulesRuleParserRuleCall_6_1_0());
					}
					lv_rules_7_0=ruleRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getStrategyRule());
						}
						add(
							$current,
							"rules",
							lv_rules_7_0,
							"xtext.Decisionmaking.Rule");
						afterParserOrEnumRuleCall();
					}
				)
			)*
		)*
		otherlv_8='}'
		{
			newLeafNode(otherlv_8, grammarAccess.getStrategyAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRuleStrategyPredefined
entryRuleStrategyPredefined returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStrategyPredefinedRule()); }
	iv_ruleStrategyPredefined=ruleStrategyPredefined
	{ $current=$iv_ruleStrategyPredefined.current; }
	EOF;

// Rule StrategyPredefined
ruleStrategyPredefined returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Strategy'
		{
			newLeafNode(otherlv_0, grammarAccess.getStrategyPredefinedAccess().getStrategyKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getStrategyPredefinedAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getStrategyPredefinedRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getStrategyPredefinedAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getStrategyPredefinedAccess().getRulesPredefinedRuleParserRuleCall_3_0());
				}
				lv_rules_3_0=rulePredefinedRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getStrategyPredefinedRule());
					}
					add(
						$current,
						"rules",
						lv_rules_3_0,
						"xtext.Decisionmaking.PredefinedRule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			otherlv_4='then'
			{
				newLeafNode(otherlv_4, grammarAccess.getStrategyPredefinedAccess().getThenKeyword_4_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getStrategyPredefinedAccess().getRulesPredefinedRuleParserRuleCall_4_1_0());
					}
					lv_rules_5_0=rulePredefinedRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getStrategyPredefinedRule());
						}
						add(
							$current,
							"rules",
							lv_rules_5_0,
							"xtext.Decisionmaking.PredefinedRule");
						afterParserOrEnumRuleCall();
					}
				)
			)*
		)*
		otherlv_6='}'
		{
			newLeafNode(otherlv_6, grammarAccess.getStrategyPredefinedAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleRule
entryRuleRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRuleRule()); }
	iv_ruleRule=ruleRule
	{ $current=$iv_ruleRule.current; }
	EOF;

// Rule Rule
ruleRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getRuleAccess().getStrategyAlgorithmParserRuleCall_0());
		}
		this_StrategyAlgorithm_0=ruleStrategyAlgorithm
		{
			$current = $this_StrategyAlgorithm_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getRuleAccess().getStrategyDecisionRuleParserRuleCall_1());
		}
		this_StrategyDecisionRule_1=ruleStrategyDecisionRule
		{
			$current = $this_StrategyDecisionRule_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRulePredefinedRule
entryRulePredefinedRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPredefinedRuleRule()); }
	iv_rulePredefinedRule=rulePredefinedRule
	{ $current=$iv_rulePredefinedRule.current; }
	EOF;

// Rule PredefinedRule
rulePredefinedRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getPredefinedRuleAccess().getStrategyAlgorithmParserRuleCall_0());
		}
		this_StrategyAlgorithm_0=ruleStrategyAlgorithm
		{
			$current = $this_StrategyAlgorithm_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPredefinedRuleAccess().getPredefinedDecisionRuleParserRuleCall_1());
		}
		this_PredefinedDecisionRule_1=rulePredefinedDecisionRule
		{
			$current = $this_PredefinedDecisionRule_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleStrategyDecisionRule
entryRuleStrategyDecisionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStrategyDecisionRuleRule()); }
	iv_ruleStrategyDecisionRule=ruleStrategyDecisionRule
	{ $current=$iv_ruleStrategyDecisionRule.current; }
	EOF;

// Rule StrategyDecisionRule
ruleStrategyDecisionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='decisionrule'
		{
			newLeafNode(otherlv_0, grammarAccess.getStrategyDecisionRuleAccess().getDecisionruleKeyword_0());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getStrategyDecisionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getStrategyDecisionRuleAccess().getDecisionruleDecisionRuleCrossReference_1_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='for'
		{
			newLeafNode(otherlv_2, grammarAccess.getStrategyDecisionRuleAccess().getForKeyword_2());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getStrategyDecisionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getStrategyDecisionRuleAccess().getTeamprofilesProfileCrossReference_3_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)+
	)
;

// Entry rule entryRulePredefinedDecisionRule
entryRulePredefinedDecisionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPredefinedDecisionRuleRule()); }
	iv_rulePredefinedDecisionRule=rulePredefinedDecisionRule
	{ $current=$iv_rulePredefinedDecisionRule.current; }
	EOF;

// Rule PredefinedDecisionRule
rulePredefinedDecisionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='decisionrule'
		{
			newLeafNode(otherlv_0, grammarAccess.getPredefinedDecisionRuleAccess().getDecisionruleKeyword_0());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPredefinedDecisionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getPredefinedDecisionRuleAccess().getDecisionruleDecisionRuleCrossReference_1_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleStrategyAlgorithm
entryRuleStrategyAlgorithm returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStrategyAlgorithmRule()); }
	iv_ruleStrategyAlgorithm=ruleStrategyAlgorithm
	{ $current=$iv_ruleStrategyAlgorithm.current; }
	EOF;

// Rule StrategyAlgorithm
ruleStrategyAlgorithm returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='algorithm'
		{
			newLeafNode(otherlv_0, grammarAccess.getStrategyAlgorithmAccess().getAlgorithmKeyword_0());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getStrategyAlgorithmRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getStrategyAlgorithmAccess().getAlgorithmAlgorithmCrossReference_1_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleDecisionRule
entryRuleDecisionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDecisionRuleRule()); }
	iv_ruleDecisionRule=ruleDecisionRule
	{ $current=$iv_ruleDecisionRule.current; }
	EOF;

// Rule DecisionRule
ruleDecisionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='decisionrule'
		{
			newLeafNode(otherlv_0, grammarAccess.getDecisionRuleAccess().getDecisionruleKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getDecisionRuleAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDecisionRuleRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='('
		{
			newLeafNode(otherlv_2, grammarAccess.getDecisionRuleAccess().getLeftParenthesisKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDecisionRuleAccess().getPrefIndAcceptedPreferenceIndicationKindEnumRuleCall_3_0());
				}
				lv_prefIndAccepted_3_0=rulePreferenceIndicationKind
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDecisionRuleRule());
					}
					add(
						$current,
						"prefIndAccepted",
						lv_prefIndAccepted_3_0,
						"xtext.Decisionmaking.PreferenceIndicationKind");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_4=')'
		{
			newLeafNode(otherlv_4, grammarAccess.getDecisionRuleAccess().getRightParenthesisKeyword_4());
		}
		(
			(
				lv_description_5_0=RULE_STRING
				{
					newLeafNode(lv_description_5_0, grammarAccess.getDecisionRuleAccess().getDescriptionSTRINGTerminalRuleCall_5_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDecisionRuleRule());
					}
					setWithLastConsumed(
						$current,
						"description",
						lv_description_5_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
	)
;

// Entry rule entryRuleAlgorithm
entryRuleAlgorithm returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAlgorithmRule()); }
	iv_ruleAlgorithm=ruleAlgorithm
	{ $current=$iv_ruleAlgorithm.current; }
	EOF;

// Rule Algorithm
ruleAlgorithm returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='algorithm'
		{
			newLeafNode(otherlv_0, grammarAccess.getAlgorithmAccess().getAlgorithmKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getAlgorithmAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAlgorithmRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='('
		{
			newLeafNode(otherlv_2, grammarAccess.getAlgorithmAccess().getLeftParenthesisKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAlgorithmAccess().getPrefIndAcceptedPreferenceIndicationKindEnumRuleCall_3_0());
				}
				lv_prefIndAccepted_3_0=rulePreferenceIndicationKind
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAlgorithmRule());
					}
					add(
						$current,
						"prefIndAccepted",
						lv_prefIndAccepted_3_0,
						"xtext.Decisionmaking.PreferenceIndicationKind");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_4=')'
		{
			newLeafNode(otherlv_4, grammarAccess.getAlgorithmAccess().getRightParenthesisKeyword_4());
		}
		otherlv_5='considersTP'
		{
			newLeafNode(otherlv_5, grammarAccess.getAlgorithmAccess().getConsidersTPKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAlgorithmAccess().getConsidersTPBOOLEANEnumRuleCall_6_0());
				}
				lv_considersTP_6_0=ruleBOOLEAN
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAlgorithmRule());
					}
					set(
						$current,
						"considersTP",
						lv_considersTP_6_0,
						"xtext.Decisionmaking.BOOLEAN");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				lv_description_7_0=RULE_STRING
				{
					newLeafNode(lv_description_7_0, grammarAccess.getAlgorithmAccess().getDescriptionSTRINGTerminalRuleCall_7_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAlgorithmRule());
					}
					setWithLastConsumed(
						$current,
						"description",
						lv_description_7_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
	)
;

// Entry rule entryRuleDesignTime
entryRuleDesignTime returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDesignTimeRule()); }
	iv_ruleDesignTime=ruleDesignTime
	{ $current=$iv_ruleDesignTime.current; }
	EOF;

// Rule DesignTime
ruleDesignTime returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='DesignTime'
		{
			newLeafNode(otherlv_0, grammarAccess.getDesignTimeAccess().getDesignTimeKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getDesignTimeAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDesignTimeAccess().getDecisionsupportDecisionSupportParserRuleCall_2_0());
				}
				lv_decisionsupport_2_0=ruleDecisionSupport
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDesignTimeRule());
					}
					set(
						$current,
						"decisionsupport",
						lv_decisionsupport_2_0,
						"xtext.Decisionmaking.DecisionSupport");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='}'
		{
			newLeafNode(otherlv_3, grammarAccess.getDesignTimeAccess().getRightCurlyBracketKeyword_3());
		}
	)
;

// Entry rule entryRuleDecisionSupport
entryRuleDecisionSupport returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDecisionSupportRule()); }
	iv_ruleDecisionSupport=ruleDecisionSupport
	{ $current=$iv_ruleDecisionSupport.current; }
	EOF;

// Rule DecisionSupport
ruleDecisionSupport returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='DecisionSupport'
		{
			newLeafNode(otherlv_0, grammarAccess.getDecisionSupportAccess().getDecisionSupportKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getDecisionSupportAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDecisionSupportRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='decidesFor'
		{
			newLeafNode(otherlv_2, grammarAccess.getDecisionSupportAccess().getDecidesForKeyword_2());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDecisionSupportRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getDecisionSupportAccess().getMakedecisionforCategoryCrossReference_3_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)+
		otherlv_4='{'
		{
			newLeafNode(otherlv_4, grammarAccess.getDecisionSupportAccess().getLeftCurlyBracketKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDecisionSupportAccess().getStratStratParserRuleCall_5_0());
				}
				lv_strat_5_0=ruleStrat
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDecisionSupportRule());
					}
					add(
						$current,
						"strat",
						lv_strat_5_0,
						"xtext.Decisionmaking.Strat");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_6='}'
		{
			newLeafNode(otherlv_6, grammarAccess.getDecisionSupportAccess().getRightCurlyBracketKeyword_6());
		}
	)
;

// Entry rule entryRuleStrat
entryRuleStrat returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStratRule()); }
	iv_ruleStrat=ruleStrat
	{ $current=$iv_ruleStrat.current; }
	EOF;

// Rule Strat
ruleStrat returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getStratAccess().getStrategyParserRuleCall_0());
		}
		this_Strategy_0=ruleStrategy
		{
			$current = $this_Strategy_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		(
			otherlv_1='Strategy'
			{
				newLeafNode(otherlv_1, grammarAccess.getStratAccess().getStrategyKeyword_1_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getStratRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getStratAccess().getStratStrategyPredefinedCrossReference_1_1_0());
					}
					ruleQualifiedName
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
			otherlv_3='withPreferenceIndication'
			{
				newLeafNode(otherlv_3, grammarAccess.getStratAccess().getWithPreferenceIndicationKeyword_1_2());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getStratAccess().getSolutionSelectedChosenPreferenceIndicationKindEnumRuleCall_1_3_0());
					}
					lv_solutionSelectedChosen_4_0=rulePreferenceIndicationKind
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getStratRule());
						}
						set(
							$current,
							"solutionSelectedChosen",
							lv_solutionSelectedChosen_4_0,
							"xtext.Decisionmaking.PreferenceIndicationKind");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_5='for'
				{
					newLeafNode(otherlv_5, grammarAccess.getStratAccess().getForKeyword_1_4_0());
				}
				(
					(
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getStratRule());
							}
						}
						{
							newCompositeNode(grammarAccess.getStratAccess().getTeamprofilesProfileCrossReference_1_4_1_0());
						}
						ruleQualifiedName
						{
							afterParserOrEnumRuleCall();
						}
					)
				)+
			)?
		)
	)
;

// Entry rule entryRuleRunTime
entryRuleRunTime returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRunTimeRule()); }
	iv_ruleRunTime=ruleRunTime
	{ $current=$iv_ruleRunTime.current; }
	EOF;

// Rule RunTime
ruleRunTime returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Runtime'
		{
			newLeafNode(otherlv_0, grammarAccess.getRunTimeAccess().getRuntimeKeyword_0());
		}
		otherlv_1='using'
		{
			newLeafNode(otherlv_1, grammarAccess.getRunTimeAccess().getUsingKeyword_1());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRunTimeRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getRunTimeAccess().getDecisionsupportDecisionSupportCrossReference_2_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getRunTimeAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRunTimeRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getRunTimeAccess().getCategoryCategoryCrossReference_4_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='{'
		{
			newLeafNode(otherlv_5, grammarAccess.getRunTimeAccess().getLeftCurlyBracketKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getRunTimeAccess().getSaddresultSADDResultParserRuleCall_6_0());
				}
				lv_saddresult_6_0=ruleSADDResult
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRunTimeRule());
					}
					add(
						$current,
						"saddresult",
						lv_saddresult_6_0,
						"xtext.Decisionmaking.SADDResult");
					afterParserOrEnumRuleCall();
				}
			)
		)+
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getRunTimeAccess().getRightCurlyBracketKeyword_7());
		}
		otherlv_8='}'
		{
			newLeafNode(otherlv_8, grammarAccess.getRunTimeAccess().getRightCurlyBracketKeyword_8());
		}
	)
;

// Entry rule entryRuleSADDResult
entryRuleSADDResult returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSADDResultRule()); }
	iv_ruleSADDResult=ruleSADDResult
	{ $current=$iv_ruleSADDResult.current; }
	EOF;

// Rule SADDResult
ruleSADDResult returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSADDResultRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getSADDResultAccess().getSaddSecurityADDCrossReference_0_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getSADDResultAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSADDResultAccess().getAltpreferencesAlternativePreferenceParserRuleCall_2_0());
				}
				lv_altpreferences_2_0=ruleAlternativePreference
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSADDResultRule());
					}
					add(
						$current,
						"altpreferences",
						lv_altpreferences_2_0,
						"xtext.Decisionmaking.AlternativePreference");
					afterParserOrEnumRuleCall();
				}
			)
		)+
		otherlv_3='}'
		{
			newLeafNode(otherlv_3, grammarAccess.getSADDResultAccess().getRightCurlyBracketKeyword_3());
		}
	)
;

// Entry rule entryRuleAlternativePreference
entryRuleAlternativePreference returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAlternativePreferenceRule()); }
	iv_ruleAlternativePreference=ruleAlternativePreference
	{ $current=$iv_ruleAlternativePreference.current; }
	EOF;

// Rule AlternativePreference
ruleAlternativePreference returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAlternativePreferenceRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getAlternativePreferenceAccess().getAlternativeAlternativeCrossReference_0_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getAlternativePreferenceAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAlternativePreferenceAccess().getPreferencesPreferenceParserRuleCall_2_0());
				}
				lv_preferences_2_0=rulePreference
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAlternativePreferenceRule());
					}
					add(
						$current,
						"preferences",
						lv_preferences_2_0,
						"xtext.Decisionmaking.Preference");
					afterParserOrEnumRuleCall();
				}
			)
		)+
		otherlv_3='}'
		{
			newLeafNode(otherlv_3, grammarAccess.getAlternativePreferenceAccess().getRightCurlyBracketKeyword_3());
		}
	)
;

// Entry rule entryRulePreference
entryRulePreference returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPreferenceRule()); }
	iv_rulePreference=rulePreference
	{ $current=$iv_rulePreference.current; }
	EOF;

// Rule Preference
rulePreference returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPreferenceRule());
					}
				}
				otherlv_0=RULE_ID
				{
					newLeafNode(otherlv_0, grammarAccess.getPreferenceAccess().getActorActorCrossReference_0_0());
				}
			)
		)
		otherlv_1='selected'
		{
			newLeafNode(otherlv_1, grammarAccess.getPreferenceAccess().getSelectedKeyword_1());
		}
		(
			(
				lv_value_2_0=RULE_INT
				{
					newLeafNode(lv_value_2_0, grammarAccess.getPreferenceAccess().getValueINTTerminalRuleCall_2_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPreferenceRule());
					}
					setWithLastConsumed(
						$current,
						"value",
						lv_value_2_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_3='rationale'
		{
			newLeafNode(otherlv_3, grammarAccess.getPreferenceAccess().getRationaleKeyword_3());
		}
		(
			(
				lv_rationale_4_0=RULE_STRING
				{
					newLeafNode(lv_rationale_4_0, grammarAccess.getPreferenceAccess().getRationaleSTRINGTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPreferenceRule());
					}
					setWithLastConsumed(
						$current,
						"rationale",
						lv_rationale_4_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
	)
;

// Entry rule entryRuleQualifiedName
entryRuleQualifiedName returns [String current=null]:
	{ newCompositeNode(grammarAccess.getQualifiedNameRule()); }
	iv_ruleQualifiedName=ruleQualifiedName
	{ $current=$iv_ruleQualifiedName.current.getText(); }
	EOF;

// Rule QualifiedName
ruleQualifiedName returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_ID_0=RULE_ID
		{
			$current.merge(this_ID_0);
		}
		{
			newLeafNode(this_ID_0, grammarAccess.getQualifiedNameAccess().getIDTerminalRuleCall_0());
		}
		(
			kw='.'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getQualifiedNameAccess().getFullStopKeyword_1_0());
			}
			this_ID_2=RULE_ID
			{
				$current.merge(this_ID_2);
			}
			{
				newLeafNode(this_ID_2, grammarAccess.getQualifiedNameAccess().getIDTerminalRuleCall_1_1());
			}
		)*
	)
;

// Rule PreferenceIndicationKind
rulePreferenceIndicationKind returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='Ranking'
			{
				$current = grammarAccess.getPreferenceIndicationKindAccess().getRankingEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getPreferenceIndicationKindAccess().getRankingEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='Rating'
			{
				$current = grammarAccess.getPreferenceIndicationKindAccess().getRatingEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getPreferenceIndicationKindAccess().getRatingEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='YesNo'
			{
				$current = grammarAccess.getPreferenceIndicationKindAccess().getYesnoEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getPreferenceIndicationKindAccess().getYesnoEnumLiteralDeclaration_2());
			}
		)
	)
;

// Rule BOOLEAN
ruleBOOLEAN returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='no'
			{
				$current = grammarAccess.getBOOLEANAccess().getNoEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getBOOLEANAccess().getNoEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='yes'
			{
				$current = grammarAccess.getBOOLEANAccess().getYesEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getBOOLEANAccess().getYesEnumLiteralDeclaration_1());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
