/*
 * generated by Xtext 2.35.0
 */
package xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import xtext.decisionmaking.Algorithm;
import xtext.decisionmaking.AlternativePreference;
import xtext.decisionmaking.DecisionRule;
import xtext.decisionmaking.DecisionSupport;
import xtext.decisionmaking.DecisionmakingPackage;
import xtext.decisionmaking.DesignTime;
import xtext.decisionmaking.GroupDecisionSession;
import xtext.decisionmaking.Import;
import xtext.decisionmaking.LibDesRun;
import xtext.decisionmaking.Library;
import xtext.decisionmaking.PredefinedDecisionRule;
import xtext.decisionmaking.Preference;
import xtext.decisionmaking.RunTime;
import xtext.decisionmaking.SADDResult;
import xtext.decisionmaking.Strat;
import xtext.decisionmaking.Strategy;
import xtext.decisionmaking.StrategyAlgorithm;
import xtext.decisionmaking.StrategyDecisionRule;
import xtext.decisionmaking.StrategyPredefined;
import xtext.services.DecisionmakingGrammarAccess;

@SuppressWarnings("all")
public class DecisionmakingSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DecisionmakingGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == DecisionmakingPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DecisionmakingPackage.ALGORITHM:
				sequence_Algorithm(context, (Algorithm) semanticObject); 
				return; 
			case DecisionmakingPackage.ALTERNATIVE_PREFERENCE:
				sequence_AlternativePreference(context, (AlternativePreference) semanticObject); 
				return; 
			case DecisionmakingPackage.DECISION_RULE:
				sequence_DecisionRule(context, (DecisionRule) semanticObject); 
				return; 
			case DecisionmakingPackage.DECISION_SUPPORT:
				sequence_DecisionSupport(context, (DecisionSupport) semanticObject); 
				return; 
			case DecisionmakingPackage.DESIGN_TIME:
				sequence_DesignTime(context, (DesignTime) semanticObject); 
				return; 
			case DecisionmakingPackage.GROUP_DECISION_SESSION:
				sequence_GroupDecisionSession(context, (GroupDecisionSession) semanticObject); 
				return; 
			case DecisionmakingPackage.IMPORT:
				sequence_Import(context, (Import) semanticObject); 
				return; 
			case DecisionmakingPackage.LIB_DES_RUN:
				sequence_LibDesRun(context, (LibDesRun) semanticObject); 
				return; 
			case DecisionmakingPackage.LIBRARY:
				sequence_Library(context, (Library) semanticObject); 
				return; 
			case DecisionmakingPackage.PREDEFINED_DECISION_RULE:
				sequence_PredefinedDecisionRule(context, (PredefinedDecisionRule) semanticObject); 
				return; 
			case DecisionmakingPackage.PREFERENCE:
				sequence_Preference(context, (Preference) semanticObject); 
				return; 
			case DecisionmakingPackage.RUN_TIME:
				sequence_RunTime(context, (RunTime) semanticObject); 
				return; 
			case DecisionmakingPackage.SADD_RESULT:
				sequence_SADDResult(context, (SADDResult) semanticObject); 
				return; 
			case DecisionmakingPackage.STRAT:
				sequence_Strat(context, (Strat) semanticObject); 
				return; 
			case DecisionmakingPackage.STRATEGY:
				sequence_Strategy(context, (Strategy) semanticObject); 
				return; 
			case DecisionmakingPackage.STRATEGY_ALGORITHM:
				sequence_StrategyAlgorithm(context, (StrategyAlgorithm) semanticObject); 
				return; 
			case DecisionmakingPackage.STRATEGY_DECISION_RULE:
				sequence_StrategyDecisionRule(context, (StrategyDecisionRule) semanticObject); 
				return; 
			case DecisionmakingPackage.STRATEGY_PREDEFINED:
				sequence_StrategyPredefined(context, (StrategyPredefined) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Algorithm returns Algorithm
	 *
	 * Constraint:
	 *     (name=ID prefIndAccepted+=PreferenceIndicationKind* considersTP=BOOLEAN description=STRING)
	 * </pre>
	 */
	protected void sequence_Algorithm(ISerializationContext context, Algorithm semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AlternativePreference returns AlternativePreference
	 *
	 * Constraint:
	 *     (alternative=[Alternative|QualifiedName] preferences+=Preference+)
	 * </pre>
	 */
	protected void sequence_AlternativePreference(ISerializationContext context, AlternativePreference semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     DecisionRule returns DecisionRule
	 *
	 * Constraint:
	 *     (name=ID prefIndAccepted+=PreferenceIndicationKind* description=STRING)
	 * </pre>
	 */
	protected void sequence_DecisionRule(ISerializationContext context, DecisionRule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     DecisionSupport returns DecisionSupport
	 *
	 * Constraint:
	 *     (name=ID makedecisionfor+=[Category|QualifiedName]+ strat+=Strat*)
	 * </pre>
	 */
	protected void sequence_DecisionSupport(ISerializationContext context, DecisionSupport semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     DesignTime returns DesignTime
	 *
	 * Constraint:
	 *     decisionsupport=DecisionSupport
	 * </pre>
	 */
	protected void sequence_DesignTime(ISerializationContext context, DesignTime semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DecisionmakingPackage.Literals.DESIGN_TIME__DECISIONSUPPORT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DecisionmakingPackage.Literals.DESIGN_TIME__DECISIONSUPPORT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDesignTimeAccess().getDecisionsupportDecisionSupportParserRuleCall_2_0(), semanticObject.getDecisionsupport());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     GroupDecisionSession returns GroupDecisionSession
	 *
	 * Constraint:
	 *     (imports+=Import* decisionSupport=LibDesRun)
	 * </pre>
	 */
	protected void sequence_GroupDecisionSession(ISerializationContext context, GroupDecisionSession semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Import returns Import
	 *
	 * Constraint:
	 *     importURI=STRING
	 * </pre>
	 */
	protected void sequence_Import(ISerializationContext context, Import semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DecisionmakingPackage.Literals.IMPORT__IMPORT_URI) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DecisionmakingPackage.Literals.IMPORT__IMPORT_URI));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getImportAccess().getImportURISTRINGTerminalRuleCall_1_0(), semanticObject.getImportURI());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LibDesRun returns LibDesRun
	 *
	 * Constraint:
	 *     (library=Library | designtime=DesignTime | runtime=RunTime)
	 * </pre>
	 */
	protected void sequence_LibDesRun(ISerializationContext context, LibDesRun semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Library returns Library
	 *
	 * Constraint:
	 *     ((name=ID decisionrules+=DecisionRule*) | algorithms+=Algorithm | strategies+=StrategyPredefined)+
	 * </pre>
	 */
	protected void sequence_Library(ISerializationContext context, Library semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PredefinedRule returns PredefinedDecisionRule
	 *     PredefinedDecisionRule returns PredefinedDecisionRule
	 *
	 * Constraint:
	 *     decisionrule=[DecisionRule|QualifiedName]
	 * </pre>
	 */
	protected void sequence_PredefinedDecisionRule(ISerializationContext context, PredefinedDecisionRule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DecisionmakingPackage.Literals.PREDEFINED_DECISION_RULE__DECISIONRULE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DecisionmakingPackage.Literals.PREDEFINED_DECISION_RULE__DECISIONRULE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPredefinedDecisionRuleAccess().getDecisionruleDecisionRuleQualifiedNameParserRuleCall_1_0_1(), semanticObject.eGet(DecisionmakingPackage.Literals.PREDEFINED_DECISION_RULE__DECISIONRULE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Preference returns Preference
	 *
	 * Constraint:
	 *     (actor=[Actor|ID] value=INT rationale=STRING)
	 * </pre>
	 */
	protected void sequence_Preference(ISerializationContext context, Preference semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DecisionmakingPackage.Literals.PREFERENCE__ACTOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DecisionmakingPackage.Literals.PREFERENCE__ACTOR));
			if (transientValues.isValueTransient(semanticObject, DecisionmakingPackage.Literals.PREFERENCE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DecisionmakingPackage.Literals.PREFERENCE__VALUE));
			if (transientValues.isValueTransient(semanticObject, DecisionmakingPackage.Literals.PREFERENCE__RATIONALE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DecisionmakingPackage.Literals.PREFERENCE__RATIONALE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPreferenceAccess().getActorActorIDTerminalRuleCall_0_0_1(), semanticObject.eGet(DecisionmakingPackage.Literals.PREFERENCE__ACTOR, false));
		feeder.accept(grammarAccess.getPreferenceAccess().getValueINTTerminalRuleCall_2_0(), semanticObject.getValue());
		feeder.accept(grammarAccess.getPreferenceAccess().getRationaleSTRINGTerminalRuleCall_4_0(), semanticObject.getRationale());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RunTime returns RunTime
	 *
	 * Constraint:
	 *     (decisionsupport=[DecisionSupport|QualifiedName] category=[Category|QualifiedName] saddresult+=SADDResult+)
	 * </pre>
	 */
	protected void sequence_RunTime(ISerializationContext context, RunTime semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SADDResult returns SADDResult
	 *
	 * Constraint:
	 *     (sadd=[SecurityADD|QualifiedName] altpreferences+=AlternativePreference+)
	 * </pre>
	 */
	protected void sequence_SADDResult(ISerializationContext context, SADDResult semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Strat returns Strat
	 *
	 * Constraint:
	 *     (strat=[StrategyPredefined|QualifiedName] solutionSelectedChosen=PreferenceIndicationKind teamprofiles+=[Profile|QualifiedName]*)
	 * </pre>
	 */
	protected void sequence_Strat(ISerializationContext context, Strat semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Rule returns StrategyAlgorithm
	 *     PredefinedRule returns StrategyAlgorithm
	 *     StrategyAlgorithm returns StrategyAlgorithm
	 *
	 * Constraint:
	 *     algorithm=[Algorithm|QualifiedName]
	 * </pre>
	 */
	protected void sequence_StrategyAlgorithm(ISerializationContext context, StrategyAlgorithm semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DecisionmakingPackage.Literals.STRATEGY_ALGORITHM__ALGORITHM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DecisionmakingPackage.Literals.STRATEGY_ALGORITHM__ALGORITHM));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStrategyAlgorithmAccess().getAlgorithmAlgorithmQualifiedNameParserRuleCall_1_0_1(), semanticObject.eGet(DecisionmakingPackage.Literals.STRATEGY_ALGORITHM__ALGORITHM, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Rule returns StrategyDecisionRule
	 *     StrategyDecisionRule returns StrategyDecisionRule
	 *
	 * Constraint:
	 *     (decisionrule=[DecisionRule|QualifiedName] teamprofiles+=[Profile|QualifiedName]+)
	 * </pre>
	 */
	protected void sequence_StrategyDecisionRule(ISerializationContext context, StrategyDecisionRule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     StrategyPredefined returns StrategyPredefined
	 *
	 * Constraint:
	 *     (name=ID rules+=PredefinedRule* rules+=PredefinedRule*)
	 * </pre>
	 */
	protected void sequence_StrategyPredefined(ISerializationContext context, StrategyPredefined semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Strategy returns Strategy
	 *     Strat returns Strategy
	 *
	 * Constraint:
	 *     (name=ID preferenceIndication=PreferenceIndicationKind rules+=Rule* rules+=Rule*)
	 * </pre>
	 */
	protected void sequence_Strategy(ISerializationContext context, Strategy semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
