grammar semcomdt.swhumanfactor.Teamprofile with org.eclipse.xtext.common.Terminals

generate teamprofile "http://www.semcomdt.swhumanfactor/Teamprofile"

import "http://www.semcomdt.xtext/swhumanfactor/Humanfactor" as humanfactor

ProfileLibrary:
	imports+=Import*
	actors+=Actor*
	profiles+=Profile*
;

Import:
	'import' importURI=STRING
;

Profile:
	name=ID
	("gathers" "{" actors+=[Actor]* "}")*
	"characterizedBy" attributes+=Attribute+
	;
Actor:
	"Actor" name=ID ":" attributes+=Attribute+
;
Attribute :
	 hfproperty=[humanfactor::HFProperty|QualifiedName] "="  hfmeasurementvalue=ValueKind
;
ValueKind:
	INT | STRING
;
QualifiedName:
	ID ('.' ID)*
;
